Sitefinity/feather-widgets

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/Index.cshtml

Added styles for Index view of Css widget

---

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs

Taxa url fix

---

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/HierarchicalTaxonomy.CategoriesList.cshtml

Changes to Taxonomies widget templates - designers and front-end

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Navigation/LanguageSelectorWidgetTests.cs

New integration test for language selector

---

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Controllers/DynamicContentController.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/DocumentsListController.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoGalleryController.cs
Telerik.Sitefinity.Frontend.News/MVC/Controllers/NewsController.cs

Fixed - QueryString - URL is not correct for paging after filtering

---

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/FlatTaxonomy/IFlatTaxonomyModel.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/HierarchicalTaxonomyModel.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/IHierarchicalTaxonomyModel.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/TaxaViewModelTreeBuilder.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs

TaxonomyModel: Implement option to display limited number of taxa #1208

---

Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/List.VideoGallery.cshtml

Specified section fro jQuery refernce

---

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/StringResources/HierarchicalTaxonomyResources.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/DesignerView.Simple.cshtml

https://github.com/Sitefinity/feather-widgets/issues/1215

Template dropdown fix #1215

---

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs

https://github.com/Sitefinity/feather/issues/1833

Uninstalled module fix 1833

---

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/HierarchicalTaxonomyModel.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/TaxaViewModelTreeBuilder.cs

Hierarchical taxa sort

---

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Models/DynamicContentModel.cs

Set default provider for dynamic content widget

---

Tests/FeatherWidgets.TestIntegration/Navigation/LanguageSelectorWidgetTests.cs

Add new language selector integration tests

---

Telerik.Sitefinity.Frontend.Media/Mvc/Helpers/ImageHelpers.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageDetailsViewModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ThumbnailViewModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.OverlayGallery.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml

https://github.com/Sitefinity/feather/issues/1865

Image gallery image size bug #1865

---

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Models/DynamicContentModel.cs

Fixed provider in detail view model for dynamic widget

---

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js

Fix comments widget whit no thread key

---

Telerik.Sitefinity.Frontend.Lists/Mvc/Controllers/ListsController.cs
Telerik.Sitefinity.Frontend.Lists/Mvc/Models/IListsModel.cs

Added UrlKeyPrefix to the ILIstModel

---

FeatherWidgets.sln
Telerik.Sitefinity.Frontend.Lists/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Controllers/FeedController.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/StringResources/FeedResources.cs
Telerik.Sitefinity.Frontend.Publishing/Properties/AssemblyInfo.cs
Telerik.Sitefinity.Frontend.Publishing/Telerik.Sitefinity.Frontend.Publishing.csproj
Telerik.Sitefinity.Frontend.Publishing/packages.config

Added feed assembly

---

Telerik.Sitefinity.Frontend.Identity/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Lists/InterfaceMappings.cs

DI improvements

---

Telerik.Sitefinity.Frontend.Publishing/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Controllers/FeedController.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Models/FeedInsertionOption.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Models/FeedModel.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Models/FeedViewModel.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Models/IFeedModel.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/StringResources/FeedResources.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Views/Feed/Feed.FeedLink.cshtml
Telerik.Sitefinity.Frontend.Publishing/Telerik.Sitefinity.Frontend.Publishing.csproj

Feed controller, model and template

---

Telerik.Sitefinity.Frontend.Publishing/Mvc/Models/FeedModel.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Models/IFeedModel.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Scripts/Feed/designerview-simple.js
Telerik.Sitefinity.Frontend.Publishing/Mvc/StringResources/FeedResources.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Views/Feed/DesignerView.Simple.cshtml

Feed designer

---

Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/NavigationModel.cs

improved nav extensibility

---

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Scripts/StyleSheet/designerview-simple.js
Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.cshtml

Fixed persisting of css MediaType

---

Telerik.Sitefinity.Frontend.Publishing/Helpers/PublishingWidgetExtensions.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Controllers/FeedController.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/StringResources/FeedResources.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Views/Feed/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Publishing/Telerik.Sitefinity.Frontend.Publishing.csproj

hide widget when feeds related module is not active

---

Tests/FeatherWidgets.TestUnit/DummyClasses/Publishing/DummyFeedController.cs
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/Publishing/FeedControllerTests.cs

FeedController unit tests added

---

Telerik.Sitefinity.Frontend.Publishing/Mvc/StringResources/FeedResources.cs
Telerik.Sitefinity.Frontend.Publishing/Mvc/Views/Feed/DesignerView.Simple.cshtml

Added message if seleced feed is deleted

---

Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/Detail.DetailPage.cshtml

added comments in ImageGallery details

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs

Return to the requested login page.

---

Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/Detail.DetailPage.cshtml

Moved comments list and comment count to suit design

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/SubscribeForm/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/SubscribeForm/SubscribeForm.cshtml

Subscribe widget styles

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Controllers/SubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Controllers/UnsubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Models/UnsubscribeForm/IUnsubscribeFormModel.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Models/UnsubscribeForm/UnsubscribeFormModel.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Models/UnsubscribeForm/UnsubscribeFormViewModel.cs

Fixed - redirect to page when unsubscribe

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/UnsubscribeForm/DesignerView.Simple.cshtml

Changes to Unsubscribe widget designer

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Models/SubscribeForm/SubscribeFormModel.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Models/UnsubscribeForm/UnsubscribeFormModel.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/StringResources/SubscribeFormResources.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/StringResources/UnsubscribeFormResources.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/SubscribeForm/SubscribeForm.SubscribeForm.cshtml

https://github.com/Sitefinity/feather/issues/2028

Already subscribed bug #2028

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/StringResources/UnsubscribeFormResources.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/SubscribeForm/SubscribeForm.SubscribeForm.cshtml
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/UnsubscribeForm/UnsubscribeFormByEmailAddress.UnsubscribeForm.cshtml
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/UnsubscribeForm/UnsubscribeFormByLink.UnsubscribeMessage.cshtml

Subscribe css

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Scripts/UnsubscribeForm/designerview-simple.js

Subscribe widget #2040

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Controllers/SubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/SubscribeForm/SubscribeForm.SubscribeForm.cshtml

Unsubscribe widget #2043

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Models/SubscribeForm/SubscribeFormModel.cs

https://github.com/Sitefinity/feather/issues/2040

Unsubscribe bug #2040

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Controllers/SubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Controllers/UnsubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/SubscribeForm/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/UnsubscribeForm/DesignerView.Simple.cshtml

https://github.com/Sitefinity/feather/issues/2046

Subscribe/Unsubscribe: If email campaign module is not licensed, designers should show error

---

Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Controllers/UnsubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/StringResources/UnsubscribeFormResources.cs
Telerik.Sitefinity.Frontend.EmailCampaingns/Mvc/Views/UnsubscribeForm/UnsubscribeFormByEmailAddress.UnsubscribeForm.cshtml

https://github.com/Sitefinity/feather-widgets/issues/1310

Unsubscribe messages #1310

---

Tests/FeatherWidgets.TestUnit/DummyClasses/Lists/DummyDocumentsListController.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/SubscribeForm/DummySubscribeFormController.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/SubscribeForm/DummySubscribeFormModel.cs
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/Subscribe/SubscribeControllerTests.cs

SubscribeFormController unit tests added

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/DesignerView.Simple.cshtml

Users list widget fix

---

Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
Telerik.Sitefinity.Frontend.Blogs/packages.config
Telerik.Sitefinity.Frontend.DynamicContent/Telerik.Sitefinity.Frontend.DynamicContent.csproj
Telerik.Sitefinity.Frontend.DynamicContent/packages.config
Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
Telerik.Sitefinity.Frontend.Identity/packages.config
Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj
Telerik.Sitefinity.Frontend.Lists/packages.config
Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
Telerik.Sitefinity.Frontend.Media/packages.config
Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj
Telerik.Sitefinity.Frontend.Navigation/packages.config
Telerik.Sitefinity.Frontend.News/Telerik.Sitefinity.Frontend.News.csproj
Telerik.Sitefinity.Frontend.News/packages.config
Telerik.Sitefinity.Frontend.Publishing/packages.config
Telerik.Sitefinity.Frontend.SocialShare/Telerik.Sitefinity.Frontend.SocialShare.csproj
Telerik.Sitefinity.Frontend.SocialShare/packages.config
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/packages.config

nuget references fixes

---

Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj

set SpecificVersion to False in project file of Blogs for some references

---

AssemblyInfoShare/SharedAssemblyInfo.cs

update asm versions to 1.2.270.1

---

Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/packages.config

Removed extra package

---

Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/packages.config

Fixed failing unit tests because of Telerik.Web.Ui

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs

Added missing commands to content block menu

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs
Tests/FeatherWidgets.TestUnit/ContentBlock/ContentBlockTests.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/ContentBlock/DummyContentBlockController.cs

Fix CB unit tests

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Profile/profile-edit.js

Change where to set form enctype for profile widget

---

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/StyleSheetController.cs
Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/Index.cshtml

Fixed css widget descirption in design mode

---

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/JavaScriptController.cs

fixed js widget appearance in the editor

---

Tests/FeatherWidgets.ClientTest/unit/DynamicContent/designerViewSimpleSpec.js
Tests/FeatherWidgets.ClientTest/unit/News/designerViewSimpleSpec.js
Tests/FeatherWidgets.ClientTest/unit/Search/designerViewSimpleSpec.js

Added pageId in expected get request for widget properties

---

Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml

adjust width of custom css fields, and dropdowns in more options

---

Telerik.Sitefinity.Frontend.SocialShare/SocialShareHelpers/SocialShareButtons.cs

Fixed social share path on item details page

---

Telerik.Sitefinity.Frontend.Search/Telerik.Sitefinity.Frontend.Search.csproj

[revert-autocomplete] - fix csproj

---

Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj

Re reverted

---

Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj

Added all specific version attributes

---

Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj

Added all specific version attributes to TestUI.Arrangements

---

Telerik.Sitefinity.Frontend.Forms/FormsVirtualRazorResolver.cs
Tests/FeatherWidgets.TestIntegration/Forms/FormsWidgetTests.cs

Form markup cachedep

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Helpers/ControllerHelpers.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/Index.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/Read.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/Write.Default.cshtml

forms fix submit

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs

Added redirect to frontend login  for Login widget

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs

fixed claim type properties

---

Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/BreadcrumbController.cs
Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/LanguageSelectorController.cs
Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/NavigationController.cs
Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/SiteSelectorController.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Controllers/FlatTaxonomyController.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Controllers/HierarchicalTaxonomyController.cs

navigation widgets should not render in indexing mode

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/LoginForm.LoginForm.cshtml

Fixed post of login form

---

Telerik.Sitefinity.Frontend.SocialShare/Mvc/Views/SocialShare/SocialShare.cshtml

Fix twitter button under SSL

---

Tests/FeatherWidgets.TestIntegration/Identity/LoginForm/LoginFormTests.cs

Added test for loginform query string params

---

Tests/FeatherWidgets.TestIntegration/Identity/LoginForm/LoginFormTests.cs

Added test for post login url in pure mvc

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/AccountActivationController.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ChangePasswordController.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ProfileController.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/UsersListController.cs

Added handle unknown action for all controllers in Identity

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ProfileController.cs

Fixed profile HandleUnknownAction

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Helpers/TextTypeHelpers.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FormFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/IFormFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/ITextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextType.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/TextField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Telerik.Sitefinity.Frontend.Forms/ValidatorPattern.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/TextFieldTests.cs

Add input type

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs

Added default title to text field

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Helpers/ControllerHelpers.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/TextField/text-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs

Fix text field validation

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/Form/designerview-simple.js

Added infinite scroll dep

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Helpers/ControllerHelpers.cs

Fixed setting of field properties

---

Telerik.Sitefinity.Frontend.Forms/FormRazorRenderer.cs
Telerik.Sitefinity.Frontend.Forms/IFormRenderer.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Default confirm message

---

Telerik.Sitefinity.Frontend.Forms/FormRazorRenderer.cs
Telerik.Sitefinity.Frontend.Forms/FormsVirtualRazorResolver.cs
Telerik.Sitefinity.Frontend.Forms/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

Extracted form rendering

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/ParagraphTextFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/RecaptchaFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/SectionHeaderFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/SubmitButtonController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/TextFieldController.cs

fix disappearing fields

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs
Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Views/ContentBlock/DesignerView.AddPersonalization.cshtml

[82PersonalizationStyling] - style of add personalised version of content block

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Form/DesignerView.Simple.cshtml

Story #168133 - FormsMvc: Style the Forms MVC widget

---

Telerik.Sitefinity.Frontend.Forms/IFormFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Helpers/ControllerHelpers.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Fix controller interface casts

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/RecaptchaField/recaptcha-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/RecaptchaField/Index.Default.cshtml

recaptcha attribute rename

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/TextField/text-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/Write.Default.cshtml

Fix input validations

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Models/ContentBlockModel.cs

Fix instructional text error in inline editing mode

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/Index.Default.cshtml

Forms widget styling

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/ParagraphTextField/ParagraphTextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/ParagraphTextField/paragraph-text-field.js

Fix paragraph validation of limitations

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Helpers/ControllerHelpers.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/RecaptchaField/recaptcha-field.js

Fix scripts for unauthenticated user

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/RecaptchaField/DesignerView.Simple.cshtml

[forms-recaptcha] - recaptcha preview added to designer

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/MultipleChoiceField/multiple-choice-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/Write.Default_Inline.cshtml

Fix multichoice behavior

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/CheckboxesField/CheckboxesFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/CheckboxesField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/Write.Default_Inline.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/Write.Default.cshtml

Set default for Checkboxes field

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/RecaptchaField/RecaptchaFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/RecaptchaField/DesignerView.Simple.cshtml

Fix error when open recaptcha designer

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/RecaptchaFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/RecaptchaField/IRecaptchaFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/RecaptchaField/RecaptchaFieldModel.cs

recaptcha is not a field

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/RecaptchaFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/RecaptchaField/RecaptchaFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Fix submit for empty captcha

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml

Fix choices edit for Checkboxes field

---

Telerik.Sitefinity.Frontend.Forms/Initializer.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/RecaptchaFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/SubmitButtonController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendFieldFallbackConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

Backend forms

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/CheckboxesField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/DropdownListField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/MultipleChoiceField/designerview-simple.js

Added error when try to add empty option

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/IFormModel.cs

captcha validation fix

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/CheckboxesField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml

Fixed required selection when default checkboxes are selected

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/MultipleChoiceField/MultipleChoiceFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/MultipleChoiceField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/DesignerView.Simple.cshtml

Fix mulitchoice field default value behaviour

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/DesignerView.Simple.cshtml

Added other checkbox in the designer

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/CheckboxesField/checkboxes-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/Write.Default_Inline.cshtml

Fixed required validation for checkboxes

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/RecaptchaField/DesignerView.Simple.cshtml

[forms-bugfixing] - add spacing before checkbox in recaptcha designer

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/IFormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/SubmitStatus.cs
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

Form settings

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/DesignerView.Simple.cshtml

[forms-bugfixing] - style other option in multiple choice

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/RecaptchaField/Index.Default.cshtml

Fixed recaptcha initial rendering in design mode

---

Telerik.Sitefinity.Frontend.Forms/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/Base/FormElementControllerBase.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/Base/FormFieldControllerBase.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/Base/IFormElementController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Helpers/ControllerHelpers.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/AllowedFileTypes.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/FileFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/FileFieldViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/IFileFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FormElementModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/IFormElementModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/IFormFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/RecaptchaField/IRecaptchaModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/SectionHeaderField/ISectionHeaderModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/SubmitButton/ISubmitButtonModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/FileField/file-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

File upload field validation

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Fix empty field submit

---

Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SectionHeaderField/DesignerView.Simple.cshtml

[forms-sh] - section header styles

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Changed null result persitant value

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/FileFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/IFileFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/FileField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/FileField/file-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/DesignerView.Simple.json
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

file field designer

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml

title of `Instructional Text` changed to `Content block` - request by @momchil

Forms bugfixin

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Please review:

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/RecaptchaController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/Recaptcha/RecaptchaModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/Write.Default.cshtml

recaptcha fixes

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/IFormElementModel.cs

Added attribute

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Helpers/ControllerHelpers.cs

Added logic to exclude instructional text from search index

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FileFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/IFileFieldModel.cs

clean file field

---

Telerik.Sitefinity.Frontend.Forms/Initializer.cs

recaptcha default keys for localhost

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/ParagraphTextField/ParagraphTextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs

Added casting to string

---

Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/DuplicateAndDeleteEmbedCodeWidgetOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/DuplicateAndDeleteJavaScriptWidgetOnPage.cs

now duplicating a widget is ordering the widgets properly and the wrong widget was deleted

fixed 2 UI tests

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/Recaptcha/RecaptchaModel.cs

null check recaptcha response

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/FileFieldModel.cs

fix file upload

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/RecaptchaController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/SubmitButtonController.cs

Excluded submit button and recaptcha from search

---

Telerik.Sitefinity.Frontend.Forms/FormRazorRenderer.cs

fix form index

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

form file field merge issues

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/CheckboxesFieldConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/MultipleChoiceFieldConfigurator.cs

backend response create issues

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs

Removed content locatable from forms widget

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/TextFieldController.cs

Text button title changed

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/TextField/text-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/Write.Default.cshtml

Fix violation messages in text field

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml

Beta82peleva

---

Telerik.Sitefinity.Frontend.Forms/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/CaptchaController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/RecaptchaController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/Captcha/CaptchaModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/Captcha/CaptchaViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/Captcha/ICaptchaModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/Captcha/captcha.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/Captcha/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Captcha/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Captcha/DesignerView.Simple.json
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Captcha/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Recaptcha/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

Initial captcha impl

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/FieldConfiguration.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendFieldFallbackConfigurator.cs

fallback to textfield

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/FileField/file-field.js

passed settings

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/FileField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/Write.Default.cshtml

Error message and 0 fixed

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/FileFieldModel.cs

Changed file types

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/FileFieldModel.cs

Fixed file size check

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/MultipleChoiceField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Recaptcha/DesignerView.Simple.cshtml

[beta82-ench] - fixes in forms requested by Momchi

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/FileField/file-field.js

Added data validator

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendFieldFallbackConfigurator.cs

Excluded captcha

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Captcha/Write.Default.cshtml

captcha js now properly built

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendFieldFallbackConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Captcha/Write.Default.cshtml
Tests/FeatherWidgets.TestUI.Arrangements/SystemSetup/SetupSitefinityForMultisiteMultilingual.cs
Tests/FeatherWidgets.TestUI.Arrangements/testArrangements.config
Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/SelectItemInDynamicWidgetFromDifferentProvider.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Templates/TemplateOperations.cs

Merge - multisite set up fix

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Removed FormsHelper usage

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/CheckboxesField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/MultipleChoiceField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/DesignerView.Simple.cshtml

[beta82-ench] - forms designers enchancements

---

Tests/FeatherWidgets.TestUI.Arrangements/Classifications/SelectAllTagsOptionAndCssClasses.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Identity/VerifySelectedRolesInUsersListOnBootstrapPage.cs
Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyListTemplatesOnBootstrap.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_BootstrapTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_FoundationTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_SemanticUITemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/Classifications/SelectAllTagsOptionAndCssClasses.cs
Tests/FeatherWidgets.TestUI.TestCases/News/FilterNewsItemFromDifferentProviderWithCategoryOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/News/SelectNewsItemFromDifferentProviderInNewsWidget.cs

Forms - fix failing UI tests

---

Telerik.Sitefinity.Frontend.Forms/FormRazorRenderer.cs

Fixed submit when two forms are one the same page

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/ParagraphTextField/DesignerView.Simple.cshtml

[beta82-pt] - style paragraph text field designer + momchi fixes

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/Form/form-ajax.js

fixed lint issues

---

FeatherWidgets.sln
Telerik.Sitefinity.Frontend.Engagement/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Engagement/Mvc/Controllers/EngagementController.cs
Telerik.Sitefinity.Frontend.Engagement/Mvc/Models/Engagement/EngagementModel.cs
Telerik.Sitefinity.Frontend.Engagement/Mvc/Models/Engagement/EngagementViewModel.cs
Telerik.Sitefinity.Frontend.Engagement/Mvc/Models/Engagement/IEngagementModel.cs
Telerik.Sitefinity.Frontend.Engagement/Mvc/Scripts/Engagement/designerview-simple.js
Telerik.Sitefinity.Frontend.Engagement/Mvc/StringResources/EngagementResources.cs
Telerik.Sitefinity.Frontend.Engagement/Mvc/Views/Engagement/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Engagement/Mvc/Views/Engagement/DesignerView.Simple.json
Telerik.Sitefinity.Frontend.Engagement/Mvc/Views/Engagement/Engagement.cshtml
Telerik.Sitefinity.Frontend.Engagement/OpenAccessNuGet.targets
Telerik.Sitefinity.Frontend.Engagement/Properties/AssemblyInfo.cs
Telerik.Sitefinity.Frontend.Engagement/Telerik.Sitefinity.Frontend.Engagement.csproj
Telerik.Sitefinity.Frontend.Engagement/app.config
Telerik.Sitefinity.Frontend.Engagement/packages.config

82 engagement widget

---

Telerik.Sitefinity.Frontend.Forms/FormsVirtualRazorResolver.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FormElementModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FormFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/IFormElementModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/IFormFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/IFormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/Write.Default.cshtml

Internal resolver and string for validation attrs

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs

Fix submit url

---

Telerik.Sitefinity.Frontend.Engagement/Telerik.Sitefinity.Frontend.Engagement.csproj
Telerik.Sitefinity.Frontend.Engagement/app.config
Telerik.Sitefinity.Frontend.Engagement/packages.config
Tests/FeatherWidgets.TestUnit/app.config

[engagement] - update sitefinity mvc reference in engagement widget

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsBackend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/ViewFormWithCheckboxesFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/ViewFormWithDropdownListFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/ViewFormWithMultipleChoiceFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithCheckboxesFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithDropdownListFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithMultipleChoiceFieldOnPageAndVerifyResponseInBackend.cs

UI tests for forms

---

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsBackend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsContentScreenWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsWrapperFacade.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/ViewFormWithContentBlockOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/ViewFormWithParagraphTextFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/ViewFormWithSectionHeaderOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithCheckboxesFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithContentBlockOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithDropdownListFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithMultipleChoiceFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithParagraphTextFieldOnPageAndVerifyResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/ViewFormWithSectionHeaderOnPageAndVerifyResponseInBackend.cs

Forms UI tests

---

Telerik.Sitefinity.Frontend.Engagement/Mvc/Controllers/EngagementController.cs
Telerik.Sitefinity.Frontend.Engagement/Mvc/Views/Engagement/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Engagement/Mvc/Views/Engagement/Engagement.Card.cshtml
Telerik.Sitefinity.Frontend.Engagement/Mvc/Views/Engagement/Engagement.Simple.cshtml
Telerik.Sitefinity.Frontend.Engagement/Telerik.Sitefinity.Frontend.Engagement.csproj

[engagement] - style engagement widget

---

Telerik.Sitefinity.Frontend.Forms/Initializer.cs

Fix control type for form widgets

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs

fixed Object moved to here message

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Fixed the pre-population of the FormCollection in the validation method of FormModel

---

Telerik.Sitefinity.Frontend.Card/Mvc/StringResources/CardResources.cs
Telerik.Sitefinity.Frontend.Card/Mvc/Views/Card/DesignerView.Simple.cshtml

[engagement] - change description label

---

Telerik.Sitefinity.Frontend.Forms/Initializer.cs

[paragraph-tb] - Paragraph textbox name changed

---

Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/Resources/ResourcesTests.cs

Added unit tests for string resources of forms and comments

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/DesignerView.Simple.cshtml

Fixed designers of file field and text field

---

Telerik.Sitefinity.Frontend.Card/Mvc/StringResources/CardResources.cs
Telerik.Sitefinity.Frontend.Forms/FormRazorRenderer.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Form/Index.cshtml
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Views/ViewsCompilationTests.cs
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/Resources/ResourcesTests.cs

Views compilation test

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Captcha/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/DropdownListField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/ParagraphTextField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/Write.Default.cshtml

Peleva fixes

---

Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerListSettingsTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerSingleItemSettingsTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/DynamicModules/DynamicModulePressArticleOperations.cs

Fixed dynamic widget tests

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/TextField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/DesignerView.Simple.cshtml

Changed default value input type for text field

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/DesignerView.Simple.cshtml

Fixed instructional text field expanding

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs

Removed excess '

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Form/Index.cshtml

Added form id to view

---

Telerik.Sitefinity.Frontend.Card/Mvc/Views/Card/DesignerView.Simple.cshtml

[card-lube] - card widget adjustments

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/TextField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/DesignerView.Simple.cshtml

Init setting dv

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/DropdownListField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/DesignerView.Simple.cshtml

New option is not selected by default

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/DesignerView.Simple.cshtml

[forms-fixes] - increase padding add-item in forms controls

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Refactoring caused by the changes in FormEntryDTO.

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/CheckboxesField/designerview-simple.js

Removed dependency between required and default value

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/DropdownListField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/DesignerView.Simple.cshtml

Fixed label while dragging checkbox field

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/CheckboxesField/Write.Default_Inline.cshtml

Fix removing of default when checkbox is required

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/IFormModel.cs
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Forms/FormEventsTests.cs

Form events

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Fix form widget when form is non published

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Tests/FeatherWidgets.TestIntegration/Forms/FormEventsTests.cs

more form event tests

---

Telerik.Sitefinity.Frontend.Forms/Initializer.cs

Added comments to the Initializer of the MVC Forms.

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SectionHeader/DesignerView.Simple.cshtml

[forms-fixes] - section header styling

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SectionHeader/DesignerView.Simple.cshtml

Fix section dropdown

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

Fixed captcha validation

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/CheckboxesField/checkboxes-field.js

fix checkboxes when required and have default value

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/IFormModel.cs

Fix form draft rendering

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs

form cached index

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/packages.config

Updated version of WebTestRunner package

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/DesignerView.Simple.cshtml

fixed submit button template binding

---

Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
Telerik.Sitefinity.Frontend.Blogs/packages.config
Telerik.Sitefinity.Frontend.Card/packages.config
Telerik.Sitefinity.Frontend.DynamicContent/Telerik.Sitefinity.Frontend.DynamicContent.csproj
Telerik.Sitefinity.Frontend.DynamicContent/packages.config
Telerik.Sitefinity.Frontend.EmailCampaigns/Telerik.Sitefinity.Frontend.EmailCampaigns.csproj
Telerik.Sitefinity.Frontend.EmailCampaigns/packages.config
Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
Telerik.Sitefinity.Frontend.Identity/packages.config
Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj
Telerik.Sitefinity.Frontend.Lists/packages.config
Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
Telerik.Sitefinity.Frontend.Media/packages.config
Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj
Telerik.Sitefinity.Frontend.Navigation/packages.config
Telerik.Sitefinity.Frontend.News/Telerik.Sitefinity.Frontend.News.csproj
Telerik.Sitefinity.Frontend.News/packages.config
Telerik.Sitefinity.Frontend.SocialShare/Telerik.Sitefinity.Frontend.SocialShare.csproj
Telerik.Sitefinity.Frontend.SocialShare/packages.config
Telerik.Sitefinity.Frontend.Taxonomies/Telerik.Sitefinity.Frontend.Taxonomies.csproj
Telerik.Sitefinity.Frontend.Taxonomies/packages.config
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/packages.config

Updated serviceStack package versions to 4.0.44

---

Telerik.Sitefinity.Frontend.Card/Telerik.Sitefinity.Frontend.Card.csproj

Fixed servicestack reference for cart

---

Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FormResources.cs

Fix forms widget resources

---

Telerik.Sitefinity.Frontend.Forms/FormsVirtualRazorResolver.cs
Telerik.Sitefinity.Frontend.Forms/Initializer.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/Base/FormElementControllerBase.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/Base/FormFieldControllerBase.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/DropdownListFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/SectionHeaderController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/SubmitButtonController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/CheckboxesFieldConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendFieldFallbackConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/Captcha/CaptchaModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/Captcha/ICaptchaModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/CheckboxesField/CheckboxesFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/CheckboxesField/ICheckboxesFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/DropdownListField/DropdownListFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/DropdownListField/IDropdownListFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FileField/FileFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FormElementModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FormFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/IFormFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/MultipleChoiceField/IMultipleChoiceFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/MultipleChoiceField/MultipleChoiceFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/ParagraphTextField/ParagraphTextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/ParagraphTextField/ParagraphTextFieldViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/SubmitButton/ISubmitButtonModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/SubmitButton/SubmitButtonModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs

stylecop issues

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Captcha/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/ParagraphTextField/DesignerView.Simple.cshtml

Fe development peleva

---

Telerik.Sitefinity.Frontend.Forms/Initializer.cs

virtual path issue workaround

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/CheckboxesFieldConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/DropdownListFieldConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/FileFieldConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/IFieldConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendConfigurators/MultipleChoiceFieldConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendFieldFallbackConfigurator.cs
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Forms/BackendConfiguratorTests.cs

Fix other choice in backend

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/Captcha/CaptchaModel.cs

workaround captcha issues in multilingual

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/CheckboxesField/checkboxes-field.js

js syntax err

---

Telerik.Sitefinity.Frontend.Blogs/app.config
Telerik.Sitefinity.Frontend.Card/app.config
Telerik.Sitefinity.Frontend.Comments/app.config
Telerik.Sitefinity.Frontend.ContentBlock/app.config
Telerik.Sitefinity.Frontend.DynamicContent/app.config
Telerik.Sitefinity.Frontend.EmailCampaigns/app.config
Telerik.Sitefinity.Frontend.Identity/app.config
Telerik.Sitefinity.Frontend.InlineClientAssets/app.config
Telerik.Sitefinity.Frontend.Lists/app.config
Telerik.Sitefinity.Frontend.Media/app.config
Telerik.Sitefinity.Frontend.Navigation/app.config
Telerik.Sitefinity.Frontend.News/app.config
Telerik.Sitefinity.Frontend.Publishing/app.config
Telerik.Sitefinity.Frontend.Search/app.config
Telerik.Sitefinity.Frontend.SocialShare/app.config
Telerik.Sitefinity.Frontend.Taxonomies/app.config
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/app.config
Tests/FeatherWidgets.TestIntegration/packages.config
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/app.config
Tests/FeatherWidgets.TestUI.Arrangements/packages.config
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/packages.config
Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj
Tests/FeatherWidgets.TestUtilities/app.config
Tests/FeatherWidgets.TestUtilities/packages.config

Update assembly versions to 1.4.370

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Forms/Fields/CheckboxesFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/DropdownListFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/ParagraphTextFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/SectionHeaderFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/TextFieldTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Forms/FormsOperations.cs

Checkboxes integration tests

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/SubmitButton/submit-button.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/PostFormMultipleTimesWhilePageLoadingAndVerifyOnlyOneResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.sln.GhostDoc.xml
Tests/FeatherWidgets.TestUI.TestCases/Forms/PostFormMultipleTimesWhilePageLoadingAndVerifyOnlyOneResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/app.config

Disabling of button when submition is in progress

---

Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
Telerik.Sitefinity.Frontend.Blogs/app.config
Telerik.Sitefinity.Frontend.Blogs/packages.config
Telerik.Sitefinity.Frontend.Card/Telerik.Sitefinity.Frontend.Card.csproj
Telerik.Sitefinity.Frontend.Card/app.config
Telerik.Sitefinity.Frontend.Card/packages.config
Telerik.Sitefinity.Frontend.Comments/Telerik.Sitefinity.Frontend.Comments.csproj
Telerik.Sitefinity.Frontend.Comments/app.config
Telerik.Sitefinity.Frontend.Comments/packages.config
Telerik.Sitefinity.Frontend.ContentBlock/Telerik.Sitefinity.Frontend.ContentBlock.csproj
Telerik.Sitefinity.Frontend.ContentBlock/app.config
Telerik.Sitefinity.Frontend.ContentBlock/packages.config
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Telerik.Sitefinity.Frontend.Forms/app.config
Telerik.Sitefinity.Frontend.Forms/packages.config
Tests/FeatherWidgets.TestIntegration/app.config
Tests/FeatherWidgets.TestUI.Arrangements/app.config
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/app.config
Tests/FeatherWidgets.TestUnit/packages.config
Tests/FeatherWidgets.TestUtilities/app.config

Upgraded newtonsoft json

---

Tests/FeatherWidgets.TestIntegration/Forms/FormsWidgetTests.cs

Fix usings order

---

Telerik.Sitefinity.Frontend.Comments/Telerik.Sitefinity.Frontend.Comments.csproj
Telerik.Sitefinity.Frontend.ContentBlock/Telerik.Sitefinity.Frontend.ContentBlock.csproj
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

Added missing refrences

---

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj
Tests/Feather.Widgets.TestUI.Framework/packages.config
Tests/FeatherWidgets.TestUI.TestCases/FeatherTestCase.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/app.config
Tests/FeatherWidgets.TestUI.TestCases/packages.config

Changed a parameter for ConfigureBrowser method due to breaking change.

Merge from TestStudioUpgrade branch. Upgraded Test Studio to 2015 Q3 (v.2015.3.1015.0). 

---

Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
Telerik.Sitefinity.Frontend.Card/Telerik.Sitefinity.Frontend.Card.csproj
Telerik.Sitefinity.Frontend.Comments/Telerik.Sitefinity.Frontend.Comments.csproj
Telerik.Sitefinity.Frontend.ContentBlock/Telerik.Sitefinity.Frontend.ContentBlock.csproj
Telerik.Sitefinity.Frontend.DynamicContent/Telerik.Sitefinity.Frontend.DynamicContent.csproj
Telerik.Sitefinity.Frontend.EmailCampaigns/Telerik.Sitefinity.Frontend.EmailCampaigns.csproj
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
Telerik.Sitefinity.Frontend.InlineClientAssets/Telerik.Sitefinity.Frontend.InlineClientAssets.csproj
Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj
Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj
Telerik.Sitefinity.Frontend.News/Telerik.Sitefinity.Frontend.News.csproj
Telerik.Sitefinity.Frontend.Publishing/Telerik.Sitefinity.Frontend.Publishing.csproj
Telerik.Sitefinity.Frontend.Search/Telerik.Sitefinity.Frontend.Search.csproj
Telerik.Sitefinity.Frontend.SocialShare/Telerik.Sitefinity.Frontend.SocialShare.csproj
Telerik.Sitefinity.Frontend.Taxonomies/Telerik.Sitefinity.Frontend.Taxonomies.csproj
Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/packages.config
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/packages.config
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/packages.config
Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj
Tests/FeatherWidgets.TestUtilities/packages.config

asm version update

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/PageBreak/PageBreakModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/PageBreak/PageBreakViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/SubmitButton/ISubmitButtonModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/SubmitButton/SubmitButtonModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/SubmitButton/SubmitButtonViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/Form/form-multi-step.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/PageBreak/Read.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/Write.Default.cshtml

#174537 - Add "Previous step" option to the submit button

---

Tests/FeatherWidgets.TestIntegration/Forms/FormsWidgetTests.cs

fixed integration test

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/Write.Default.cshtml

Fix submit jquery

---

Telerik.Sitefinity.Frontend.Card/Mvc/Models/Card/CardModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs
Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/EmbedCode/EmbedCodeModel.cs

Changed GetViewModel methods to virtual

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/Form/form-multi-step.js

#174669 - Validate user input before going forward to the next screen

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/PageBreak/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/PageBreak/Read.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml

Styled designers of Page break and SubmitButtons forms widgets

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/PageBreak/Read.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/Write.Default.cshtml

Sf90forms peleva

---

Telerik.Sitefinity.Frontend.Forms/Initializer.cs
Telerik.Sitefinity.Frontend.Forms/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/NavigationFieldController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/PageBreakController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/BackendFieldFallbackConfigurator.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/NavigationField/FormPage.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/NavigationField/INavigationFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/NavigationField/NavigationFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/NavigationField/NavigationFieldViewModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/NavigationField/designerview-simple.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/NavigationField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/NavigationField/DesignerView.Simple.json
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/NavigationField/Read.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

Sf90 forms navigation

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusViewModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginButton.cshtml
Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginName.cshtml

login status update

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/Form/form-multi-step.js
Telerik.Sitefinity.Frontend.Forms/Mvc/StringResources/FieldResources.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/PageBreak/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/PageBreak/Read.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/Write.Default.cshtml

#174854 - MVC Submit Field: The possitions of Submit button and Previous step should be changed,
#174855 - MVC Submit Field: The message should be changed from Allow users to step backward to If it is a multipage form, dispay a link to the previous step

Fix for bugs:

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/NavigationFieldController.cs

#174894 MVC form with navigation field, throws exception in the backend

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Identity/LoginStatus/LoginTests.cs

added integr test for login status

---

Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerSingleItemSettingsTests.cs

fix dynamic widget integr tests

---

Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerListSettingsTests.cs

stabilize dyn widget integr test

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestUI.Arrangements/CommentsAndReviews/SubscribeUserForCommentsNotificationAndVerifyReceivedEmail.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/packages.config
Tests/FeatherWidgets.TestUI.TestCases/app.config
Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj

Fix notif ui tests

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/NavigationFieldController.cs

Replace "ControlId" with FormDraftControl constant.

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/NavigationField/navigation-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/PageBreak/page-break.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/NavigationField/Read.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

#175346 Add and use "form-page-changed" event for updating navigation  field in the front end.

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Forms/Fields/NavigationFieldTests.cs

Included test files that were previously unintentionally excluded.

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/PageBreak/page-break.js

Update page break index on "from-page-changed". 

---

Tests/FeatherWidgets.TestIntegration/Forms/FormsResponsesTests.cs

Unignored responses tests

---

Tests/FeatherWidgets.TestIntegration/Forms/Fields/SectionHeaderFieldTests.cs

Changed assertion

---

Tests/FeatherWidgets.TestUnit/DummyClasses/Forms/NavigationField/DummyNavigationFieldController.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/Forms/NavigationField/NavigationDummyHttpContext.cs
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/Forms/NavigationField/NavigationFieldTests.cs

Added unit tests for Form navigation field.

---

Tests/FeatherWidgets.TestUtilities/CommonOperations/Forms/FormsOperations.cs

#175551 FormsOperations()).CreateFormWithWidgets() should be fixed

---

Tests/FeatherWidgets.TestIntegration/Forms/Fields/PageBreakTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Forms/FormsOperations.cs

#175549 Added methods to FormOperations for creating forms with widgets in header, body and footer placeholders.

---

Telerik.Sitefinity.Frontend.Forms/FormRazorRenderer.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/NavigationField/navigation-field.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/PageBreak/page-break.js
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/SubmitButton/Write.Default.cshtml
Tests/FeatherWidgets.TestIntegration/Forms/Fields/PageBreakTests.cs

Refactor multipage form decoration

---

Tests/FeatherWidgets.TestUtilities/CommonOperations/Forms/FormsOperations.cs

#175549 Fixed generating identical ID for fields in different placeholders.

---

Tests/FeatherWidgets.TestIntegration/Forms/BackendConfiguratorTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/CheckboxesFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/DropdownListFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/NavigationFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/PageBreakTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/ParagraphTextFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/SectionHeaderFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/Fields/TextFieldTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/FormEventsTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/FormsResponsesTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/FormsWidgetTests.cs

Fixed integration tests.

---

Tests/FeatherWidgets.TestIntegration/Forms/Fields/NavigationFieldTests.cs

Added integration test for NavigationFieldController.

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/CardWidget/CardEditScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/CardWidget/CardWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/CardWidget/CardWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/CardWidget/AddPersonalizedVersionOfCardWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/CardWidget/ChangeAdvancedSettingsOfCardWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/CardWidget/ChangeCardWidgetTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/CardWidget/CreateWidgetTemplateAndSetTheTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/CardWidget/AddPersonalizedVersionOfCardWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/CardWidget/ChangeAdvancedSettingsOfCardWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/CardWidget/ChangeCardWidgetTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/CardWidget/CreateWidgetTemplateAndSetTheTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Card widget ui tests

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsBackend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsContentScreenWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/EditNextStepButton.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/VerifyHeaderAndFooter.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/VerifyRemoveHeaderAndFooter.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/EditNextStepButton.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/VerifyHeaderAndFooter.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/VerifyRemoveHeaderAndFooter.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Forms/FormsOperations.cs

Added 3 UI tests for forms.

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Scripts/NavigationField/navigation-field.js

#176040 Add css class, so that the user can style completed steps in the navigation.

---

Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/EditPageWithMultipageFormsViaInlineEditing.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/EditPageWithMultipageFormsViaInlineEditing.cs

Add new UI test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsBackend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsContentScreenWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/EnableDisablePreviousStepOptionToSubmitButtonAndChangeTitle.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/TwoMultipageFormsOnTheSamePage.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/EnableDisablePreviousStepOptionToSubmitButtonAndChangeTitle.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/TwoMultiPageFormsOnTheSamePage.cs

Multipage forms ui tests 

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/Navigation/AddFormNavigationField.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/AddFormNavigationField.cs

Added UI test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsBackend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsContentScreenWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/PreviewMultipageForm.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/Navigation/ChangeAdvancedSettingsOfFormNavigationAndSetCssClass.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/Navigation/ChangeFormNavigationTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/PreviewMultipageForm.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/ChangeAdvancedSettingsOfFormNavigationAndSetCssClass.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/ChangeFormNavigationTemplate.cs
Tests/FeatherWidgets.TestUtilities/Data/Forms/Read.DefaultFileNavigation.cshtml
Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj

Added new UI tests for multipage forms

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsBackend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsMap.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/FeatherGlobals.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsContentScreenWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/DeleteFormFieldInUseVerityFrontend.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/DeleteFormInUseVerifyFrontend.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/EditDraftFormVerifyPreview.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/EditFormSaveDraftThenPublishVerifyFrontendHybrid.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/PublishUnpublishFormInUseVerifyFrontend.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/SubmitPreviewFormVerifyResponses.cs
Tests/FeatherWidgets.TestUI.Arrangements/Forms/VerifyPreviewWhileCreatingForm.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/DeleteFormFieldInUseVerityFrontend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/DeleteFormInUseVerifyFrontend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/DeleteFormInUseVerifyFrontendHybrid.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/EditDraftFormVerifyPreview.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/EditFormSaveDraftThenPublishVerifyFrontend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/EditFormSaveDraftThenPublishVerifyFrontendHybrid.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/PostFormMultipleTimesWhilePageLoadingAndVerifyOnlyOneResponseInBackend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/PublishUnpublishFormInUseVerifyFrontend.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/PublishUnpublishFormInUseVerifyFrontendHybrid.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/SubmitPreviewFormVerifyResponses.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/VerifyPreviewWhileCreatingForm.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Forms/FormsOperations.cs

Updated UI tests, added new test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/VerifyFormPagesNumbers.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/VerifyFormPagesNumbers.cs

Added UI test.

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsContentScreenWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/MultiPageForms/MovePageBreakToHeaderAndFooter.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/MovePageBreakToHeaderAndFooter.cs

Multi forms ui tests new

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/VerifyValidationContentFields.cs

Added verification

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsContentScreenWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/AddPageBreakToForm.cs

Add verification to cover a case from the checklist.

---

Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/CreateFormResponseForMultipageForm.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/PreviewMultipageForm.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/MultiPageForms/TwoMultiPageFormsOnTheSamePage.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/AddAndRemoveNewPage.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/AddFormNavigationField.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/DeleteNavigationFromForm.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/DuplicateNavigationForm.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/EditNavigationLabels.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/Navigation/EditNavigationLabelsButCancel.cs

Fixed UI tests.

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/MediaSelectorBaseWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/CardWidget/ChangeCardWidgetTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/app.config

card ui test fix

---

Tests/FeatherWidgets.TestUI.TestCases/CardWidget/AddCardWidgetOnPageTemplate.cs

fixed one more card test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/EmailCampaigns/SubscribeFormEditScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/EmailCampaigns/SubscribeFormWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs

fixed mailing list ui tests

---

Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Telerik.Sitefinity.Frontend.Forms/packages.config

fixed servicestack references

---

Tests/FeatherWidgets.TestUI.Arrangements/CommentsAndReviews/SubscribeUserForReviewsNotificationAndVerifyReceivedEmail.cs

fixed review notification test

---

Tests/FeatherWidgets.TestUI.Arrangements/CommentsAndReviews/SubscribeUserForReviewsNotificationAndVerifyReceivedEmail.cs
Tests/FeatherWidgets.TestUI.TestCases/app.config

notifications tests fix

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Classifications/TagsWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Classifications/ClassificationsWrapper.cs

stabilized tags cloud test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Identity/LoginFormWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Selectors/SelectorsWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Identity/LoginFormWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Identity/RegistrationWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/RegisterNewUserAndLoginTheUser.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/ValidateAllFieldsInRegistrationWidget.cs

identity tests stabilization

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Classifications/TagsWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/Classifications/SelectAllTagsOptionAndCssClasses.cs

stabilize tag options test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/ImagePropertiesWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/MediaPropertiesBaseWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/MediaSelectorBaseWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorMediaWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/CardWidget/AddCardWidgetOnPageBasedOnBootstrapTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/ValidateAllFieldsInRegistrationWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/MediaWidgets/ImageWidgetInsertImageWithCustomThumbnail.cs

stabilizing tests

---

Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Horizontal.cshtml
Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Sitemap.cshtml
Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Tabs.cshtml
Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Vertical.cshtml

Navigation fixes peleva

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs

Fixed login status error message

---

Telerik.Sitefinity.Frontend.Forms/FormsDefinitionsExtender.cs

Conditional form settings extending

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml

Fixed registration post when another profile widget on the page

---

Telerik.Sitefinity.Frontend.Forms/FormsDefinitionsExtender.cs
Telerik.Sitefinity.Frontend.Forms/Initializer.cs
Telerik.Sitefinity.Frontend.Forms/Properties/AssemblyInfo.cs
Telerik.Sitefinity.Frontend.Forms/Startup.cs
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj

Definition extending now on preapp start

---

AssemblyInfoShare/SharedAssemblyInfo.cs
LICENSE.md
README.md

Updated readme, license and assembly info share copyright year

---

AssemblyInfoShare/SharedAssemblyInfo.cs
LICENSE.md
README.md

Updated copyright info

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Views/PrecompilationFilterAttribute.cs
Tests/FeatherWidgets.TestIntegration/Views/PrecompilationTests.cs

Precompilation tests

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Navigation/NavigationWidgetFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Navigation/NavigationWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/Navigation/LightNavigationAndMvcNavigation.cs

Fix UI tests

---

Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
Telerik.Sitefinity.Frontend.Blogs/packages.config
Telerik.Sitefinity.Frontend.Card/Telerik.Sitefinity.Frontend.Card.csproj
Telerik.Sitefinity.Frontend.Card/packages.config
Telerik.Sitefinity.Frontend.DynamicContent/Telerik.Sitefinity.Frontend.DynamicContent.csproj
Telerik.Sitefinity.Frontend.DynamicContent/packages.config
Telerik.Sitefinity.Frontend.EmailCampaigns/Telerik.Sitefinity.Frontend.EmailCampaigns.csproj
Telerik.Sitefinity.Frontend.EmailCampaigns/packages.config
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Telerik.Sitefinity.Frontend.Forms/packages.config
Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
Telerik.Sitefinity.Frontend.Identity/packages.config
Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj
Telerik.Sitefinity.Frontend.Lists/packages.config
Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
Telerik.Sitefinity.Frontend.Media/packages.config
Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj
Telerik.Sitefinity.Frontend.Navigation/packages.config
Telerik.Sitefinity.Frontend.News/Telerik.Sitefinity.Frontend.News.csproj
Telerik.Sitefinity.Frontend.News/packages.config
Telerik.Sitefinity.Frontend.SocialShare/Telerik.Sitefinity.Frontend.SocialShare.csproj
Telerik.Sitefinity.Frontend.SocialShare/packages.config
Telerik.Sitefinity.Frontend.Taxonomies/Telerik.Sitefinity.Frontend.Taxonomies.csproj
Telerik.Sitefinity.Frontend.Taxonomies/packages.config
Tests/FeatherWidgets.TestIntegration/app.config
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/packages.config
Tests/FeatherWidgets.TestUtilities/app.config

Upgraded ServiceStack to 4.0.52

---

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsMap.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsPropertiesScreenBaseFeather.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsContentScreenWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Forms/DeactivateAndUninstallMarketoModuleAndCreateAForm.cs
Tests/FeatherWidgets.TestUI.Arrangements/Navigation/LanguageSelectorXssAttack.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Forms/DeactivateAndUninstallMarketoModuleAndCreateAForm.cs
Tests/FeatherWidgets.TestUI.TestCases/Navigation/LanguageSelectorXssAttack.cs

Added new UI tests

---

Tests/FeatherWidgets.TestUI.Arrangements/Classifications/DuplicateAndDeleteCategoriesWidgetFromPage.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Classifications/DuplicateAndDeleteCategoriesWidgetFromPage.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Ui test categories

---

Tests/FeatherWidgets.TestUI.TestCases/Classifications/FilterCategoriesByContentTypeDocuments.cs

Remove test from classifications category

---

Tests/FeatherWidgets.TestUI.Arrangements/Classifications/DuplicateAndDeleteTagsWidgetFromPage.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Classifications/DuplicateAndDeleteTagsWidgetFromPage.cs
Tests/FeatherWidgets.TestUI.TestCases/Classifications/FilterCategoriesByContentTypeDocuments.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Ui tests tag

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/CommentsAndReviews/CommentsAndReviewsCommonWrapper.cs

Fix UI tests for comments

---

Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/NavigationModel.cs

Added root node

---

Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/CheckSelectorsAfterSelectUnselectAndUNPublishingDynamicItem.cs
Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/InvalidateCacheWhenAddNewItem.cs
Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/CheckSelectorsAfterSelectUnselectAndUNPublishingDynamicItem.cs
Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/InvalidateCacheWhenAddNewItem.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/DynamicModules/DynamicModulePressArticleOperations.cs

Fix dynamic UI tests

---

Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/NavigationModel.cs

Cache deps redone

---

Tests/FeatherWidgets.TestUI.Arrangements/CommentsAndReviews/SubscribeUserForCommentsNotificationAndVerifyReceivedEmail.cs

Fix comments UI test

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs
Tests/FeatherWidgets.TestIntegration/Identity/LoginStatus/LoginTests.cs

fix login status routing

---

Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_ApplyCssClass.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_BootstrapTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_FoundationTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_NonAuthenticatedUser.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_SemanticUITemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_SortingOnFrontend.cs
Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/SelectImagesFromSelectedLibraryInSelectedPage.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_ApplyCssClass.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_BootstrapTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_FoundationTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_NonAuthenticatedUser.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SemanticUITemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SortingOnFrontend.cs

Fixes UI tests for Search and Images

---

Tests/FeatherWidgets.TestIntegration/SearchResults/SearchResultsWidgetTests.cs

Generate unique search index name for each test + changed the delete
index method.

Fixed Search integration tests.

---

Tests/FeatherWidgets.TestIntegration/SearchResults/SearchResultsWidgetTests.cs

Reaplied 9c4f8ca0d1c63b034b224d6be34efabf74159f2b

---

Tests/FeatherWidgets.TestIntegration/Navigation/NavigationWidgetPageSelectionModeTests.cs

Nav tests unstable

---

Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsAllTypesTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsContentLocationServiceTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerContentTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerContentWithListSettingsTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerListSettingsTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerSingleItemSettingsTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsFilterByRelatedDataTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsPageTemplateTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsRoutingTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/OldDynamicWidgetsWithFeatherTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/DynamicModules/DynamicModuleModule2Operations.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/DynamicModules/DynamicModulesOperations.cs

Fixing the failing integration tests related to the Module Builder functionality.

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs

Fix Forms UI tests

---

Tests/FeatherWidgets.TestUI.TestCases/DocumentsList/FilterDocumentsWithCategoryTagAndDateOnPage.cs

Fix ui test filter documents

---

Tests/FeatherWidgets.TestUI.Arrangements/Identity/LoginAndVerifyUserStatusOnTheSamePage.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/LoginFormAndLoginStatusOnTheSamePage.cs

fixed UI test LoginAndVerifyUserStatusOnTheSamePage

---

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js

Check if Title is available

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Lists/ListsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/packages.config
Tests/FeatherWidgets.TestUI.Arrangements/testArrangements.config
Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/AddContentToContentBlockWidgetViaCreateContentOptionOnThePage.cs

Ui test fix

---

Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DocumentsList/DummyDocumentsListModel.cs
Tests/FeatherWidgets.TestUnit/Media/DocumentsList/DocumentControllerTests.cs

fixed unit test

---

Tests/FeatherWidgets.TestUI.Arrangements/Packaging/DynamicContent/ImportModuleWithEditedWidgetTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/Packaging/DynamicContent/ImportModuleWithEditedWidgetTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/Packaging/StaticContent/BlogPosts/ImportEditedWidgetTemplateBlogStructure.cs
Tests/FeatherWidgets.TestUI.TestCases/Packaging/StaticContent/Libraries/ImportEditedWidgetTemplateLibrariesStructure.cs
Tests/FeatherWidgets.TestUI.TestCases/Packaging/StaticContent/ListItems/ImportEditedWidgetTemplateListsStructure.cs
Tests/FeatherWidgets.TestUI.TestCases/Packaging/StaticContent/News/ImportEditedWidgetTemplateNewsStructure.cs

Fix UI tests for widget templates

---

FeatherWidgets.sln
Telerik.Sitefinity.Frontend.Events/Mvc/Controllers/EventsController.cs
Telerik.Sitefinity.Frontend.Events/Properties/AssemblyInfo.cs
Telerik.Sitefinity.Frontend.Events/Telerik.Sitefinity.Frontend.Events.csproj
Telerik.Sitefinity.Frontend.Events/app.config
Telerik.Sitefinity.Frontend.Events/packages.config
Telerik.Sitefinity.Frontend.Events/razorgenerator.directives

Events widget init

---

Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Scripts/Designer/modal-dialog.js
Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Views/ContentBlock/DesignerView.UseShared.cshtml
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/FileField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Form/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/ParagraphTextField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/TextField/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/DocumentsList/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/DesignerView.Simple.cshtml
Tests/FeatherWidgets.TestUI.TestCases/News/AddNewsWidgetToPageVerifyViewPermissions.cs

Angular UI Bootstrap update

---

Telerik.Sitefinity.Frontend.Events/Mvc/Controllers/EventController.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/IEventModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Views/Event/Detail.Default.cshtml
Telerik.Sitefinity.Frontend.Events/Telerik.Sitefinity.Frontend.Events.csproj

Event details

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs
Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Models/ContentBlockModel.cs
Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Models/IContentBlockModel.cs
Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Views/ContentBlock/Default.cshtml

Adding css class for the content block widget wrapper element

---

Tests/FeatherWidgets.TestIntegration/ContentBlock/ContentBlockWidget.cs

Adding integration tests for verifying page statistics when share or un-share content at content block widget.

---

Tests/FeatherWidgets.TestIntegration/ContentBlock/ContentBlockWidget.cs

Adding check for WrapperCssClass property in AdvancedSettings Integration test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockWidgetScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/ContentBlockWidgetVerifyLinksInEditorToolbar.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ContentBlockWidgetVerifyLinksInEditorToolbar.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/app.config

Bug #182945 - added ui test for Content Block widget

---

Tests/FeatherWidgets.TestIntegration/Events/EventExportsTests.cs
Tests/FeatherWidgets.TestIntegration/Events/EventWidgetFilteringTests.cs
Tests/FeatherWidgets.TestIntegration/Events/EventWidgetTests.cs
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj

Event widget

---

Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventHelper.cs
Tests/FeatherWidgets.TestIntegration/Events/EventDatesFormatTests.cs

Added minutes for the new wireframes and fixed tests

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs
Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Models/ContentBlockModel.cs
Tests/FeatherWidgets.TestIntegration/ContentBlock/ContentBlockWidget.cs

Fix bug #188823  Content Block widget text is not shown in preview mode and Edit mode

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockWidgetScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/ContentBlockWidgetAdvancedSettingsWrapperCssClassProperty.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/News/VerifyNewsItemsWhenOpenDetailsModeOfDynamicItem.cs
Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ContentBlockWidgetAdvancedSettingsWrapperCssClassProperty.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/News/VerifyNewsItemsWhenOpenDetailsModeOfDynamicItem.cs

Added ui test for bugID 144077 and bugID 176774

---

Build/FeatherPrecompilation.targets
Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
Telerik.Sitefinity.Frontend.Card/Telerik.Sitefinity.Frontend.Card.csproj
Telerik.Sitefinity.Frontend.Comments/Telerik.Sitefinity.Frontend.Comments.csproj
Telerik.Sitefinity.Frontend.ContentBlock/Telerik.Sitefinity.Frontend.ContentBlock.csproj
Telerik.Sitefinity.Frontend.DynamicContent/Telerik.Sitefinity.Frontend.DynamicContent.csproj
Telerik.Sitefinity.Frontend.EmailCampaigns/Telerik.Sitefinity.Frontend.EmailCampaigns.csproj
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
Telerik.Sitefinity.Frontend.InlineClientAssets/Telerik.Sitefinity.Frontend.InlineClientAssets.csproj
Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj
Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj
Telerik.Sitefinity.Frontend.News/Telerik.Sitefinity.Frontend.News.csproj
Telerik.Sitefinity.Frontend.Publishing/Telerik.Sitefinity.Frontend.Publishing.csproj
Telerik.Sitefinity.Frontend.Search/Telerik.Sitefinity.Frontend.Search.csproj
Telerik.Sitefinity.Frontend.SocialShare/Telerik.Sitefinity.Frontend.SocialShare.csproj
Telerik.Sitefinity.Frontend.Taxonomies/Telerik.Sitefinity.Frontend.Taxonomies.csproj

Fix npm build hierarchy

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/CardWidget/CardWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/CardWidget/AddCardWidgetOnPageBasedOnBootstrapTemplate.cs

Added additional steps to Card widget UI test

---

package.json

updated jasmine

---

Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/Event/designerview-simple.js

Sort expression when set manually persisted

---

Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventHelper.cs
Tests/FeatherWidgets.TestIntegration/Events/EventDatesFormatTests.cs

Tests completed and helpers refactored for better readability

---

Telerik.Sitefinity.Frontend.Events/Mvc/Views/Event/Detail.Default.cshtml

Event details razor errors fix

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Identity/LoginFormEditScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Identity/LoginFormFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Identity/LoginFormWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Identity/LoginFormWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Identity/VerifyLoginWidgetToTemplateWhenOpenItemDetailViewAndForgotPassword.cs
Tests/FeatherWidgets.TestUI.Arrangements/Identity/VerifyLoginWidgetWhenOpenItemDetailViewAndForgotPassword.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifyLoginWidgetToTemplateWhenOpenItemDetailViewAndForgotPassword.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifyLoginWidgetWhenOpenItemDetailViewAndForgotPassword.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs

Added ui tests for bugID 165426

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml
Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml

Preventing submit in preview and design mode

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Widgets/WidgetDesignerScreen.cs
Tests/FeatherWidgets.TestUI.TestCases/app.config

Fix ui tests widget designer tab error

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Classifications/CategoriesWidgetEditScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Forms/FormsBackend.cs

Included other anchor tag class template fixes

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Profile/profile-edit.js
Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/ProfileResources.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml
Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml

Preview mode submit

---

Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventHelper.cs

Event end using all day event end

---

Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/EditContentBlockWidgetWithCustomTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/EditContentBlockWidgetWithCustomTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Added ui test for bugID166914-content block breaks on custom bootstrap BT

---

Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventModel.cs

codeNo end date fix

---

Tests/FeatherWidgets.TestIntegration/Navigation/NavigationWidgetPageTemplateTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Templates/TemplateOperations.cs

Added integration test

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/FormFieldModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/IFormFieldModel.cs

Include MVC forms DEC tracking

---

Tests/FeatherWidgets.TestUtilities/CommonOperations/PageInvoker.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/PageInvokerRegion.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs
Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj

PageInvokerRegion class added. PageInvoker class changed to use PageInvokerRegion. PagesOperations.CreatePageWithControl() creates local PageContentGenerator only  if it's not already created.
Code Review:

PageInvokerRegion class added

---

Telerik.Sitefinity.Frontend.Events/Mvc/Controllers/EventController.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/IEventModel.cs
Telerik.Sitefinity.Frontend.Taxonomies/Helpers/ContentTypeExtensions.cs
Telerik.Sitefinity.Frontend.Taxonomies/Mvc/StringResources/FlatTaxonomyResources.cs
Tests/FeatherWidgets.TestUI.TestCases/app.config

Events in taxonomy widget

---

Telerik.Sitefinity.Frontend.EmailCampaigns/Mvc/Controllers/SubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaigns/Mvc/Models/SubscribeForm/SubscribeFormViewModel.cs
Telerik.Sitefinity.Frontend.EmailCampaigns/Mvc/Models/UnsubscribeForm/UnsubscribeFormViewModel.cs
Tests/FeatherWidgets.TestIntegration/EmailCampaigns/SubscribeFormTests.cs
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/TestCategories.cs

Only SubscribeForm was vulnerable.
Code review:

#186463 - Post param injection prevented. SubscribeFormTests integration test added.

---

Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventHelper.cs

Refactoring complete

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/VideoGallery/VideoGalleryWrapper.cs

Fixed html element selection

---

Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventHelper.cs

Fixed integration tests all day event end time calculation

---

Tests/FeatherWidgets.TestUI.Arrangements/Events/EventsTestsCommon.cs

fix ui test for UI

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendCommonWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/News/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForNewsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/News/VerifyPagingOnFrontendPageForNewsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/News/VerifyUseLimitListSettingsOnFrontendPageForNewsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/News/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForNewsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/News/VerifyPagingOnFrontendPageForNewsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/News/VerifyUseLimitListSettingsOnFrontendPageForNewsWidget.cs

#143781 - Added ui tests for pagination settings in News widget

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/Forms/ContentBlock/ViewFormWithContentBlockOnPageAndVerifyResponseInBackend.cs

Fix UI tests for forms

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Blogs/BlogsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/Blogs/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForBlogsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Blogs/VerifyPagingOnFrontendPageForBlogsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Blogs/VerifyUseLimitListSettingsOnFrontendPageForBlogsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForEventsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyPagingOnFrontendPageForEventsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyUseLimitListSettingsOnFrontendPageForEventsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Blogs/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForBlogsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Blogs/VerifyPagingOnFrontendPageForBlogsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Blogs/VerifyUseLimitListSettingsOnFrontendPageForBlogsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForEventsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyPagingOnFrontendPageForEventsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyUseLimitListSettingsOnFrontendPageForEventsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs

#143781 - Added ui tests for Blogs widget and Events widget

---

Telerik.Sitefinity.Frontend.EmailCampaigns/Mvc/Controllers/SubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaigns/Telerik.Sitefinity.Frontend.EmailCampaigns.csproj
Telerik.Sitefinity.Frontend.EmailCampaigns/packages.config

#186466 AntiXssLibrary added. SubscribeForm Widget - email value is now encoded before rendering.

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Forms/FormsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/Common/DeactivateFeatherAndVerifyFormsMvcOption.cs
Tests/FeatherWidgets.TestUI.Arrangements/Common/UninstallFeatherAndVerifyFormsMvcOption.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Common/DeactivateFeatherAndVerifyFormsMvcOption.cs
Tests/FeatherWidgets.TestUI.TestCases/Common/UninstallFeatherAndVerifyFormsMvcOption.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Adding UI tests

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Tests/FeatherWidgets.TestIntegration/Forms/FormsWidgetTests.cs

Fixed NeedsRedirect property in FormModel

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListModel.cs
Telerik.Sitefinity.Frontend.Search/Mvc/Models/SearchResultsModel.cs

Changed limitcount default value

---

Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Identity/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForUsersListWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Identity/VerifyPagingOnFrontendPageForUsersListWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Identity/VerifyUseLimitListSettingsOnFrontendPageForUsersListWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForUsersListWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifyPagingOnFrontendPageForUsersListWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifyUseLimitListSettingsOnFrontendPageForUsersListWidget.cs

#143781 - Added ui tests for pagination for UsersList widget

---

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Controllers/DynamicContentController.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/DocumentsListController.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoGalleryController.cs
Telerik.Sitefinity.Frontend.News/MVC/Controllers/NewsController.cs

Changed resolving of query string in pager urls

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Models/IFormModel.cs
Tests/FeatherWidgets.TestIntegration/Forms/FormsResponsesTests.cs
Tests/FeatherWidgets.TestIntegration/Forms/FormsWidgetTests.cs

Added cache dependency to form widget, enable ignored integration tests which depends on Sitefinity 9.0

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormViewModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileEditViewModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationViewModel.cs

Restrict binding for widget view models

---

Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForSearchResultsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifyPagingOnFrontendPageForSearchResultsWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifyUseLimitListSettingsOnFrontendPageForSearchResultsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifyNoLimitAndPaginationListSettingsOnFrontendPageForSearchResultsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifyPagingOnFrontendPageForSearchResultsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifyUseLimitSettingsOnFrontendPageForSearchResultsWidget.cs

#143781 - Added ui tests for pagination for SearchResults widget

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Navigation/NavigationWidgetEditScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Navigation/NavigationWidgetFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Navigation/NavigationWidgetEditWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Navigation/NavigationWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Navigation/BreadcrumbDetailBlogPostItemVirtualNodes.cs
Tests/FeatherWidgets.TestUI.Arrangements/Navigation/BreadcrumbDetailEventItemVirtualNodes.cs
Tests/FeatherWidgets.TestUI.Arrangements/Navigation/BreadcrumbDetailImageItemDocumentItemVideoItemVirtualNodes.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Navigation/BreadcrumbDetailBlogPostItemVirtualNodes.cs
Tests/FeatherWidgets.TestUI.TestCases/Navigation/BreadcrumbDetailEventItemVirtualNodes.cs
Tests/FeatherWidgets.TestUI.TestCases/Navigation/BreadcrumbDetailImageItemDocumentItemVideoItemVirtualNodes.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs

#174260 - Added ui tests for VirtualNodes property for Breadcrumb widget

---

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml

sf-title parameter added to the list selector with Content type Display name as value

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Widgets/WidgetDesignerScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs

Fixed ui test VerifyTitleOnSelectContentDialogForDynamicWidget

---

Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerListSettingsTests.cs
Tests/FeatherWidgets.TestIntegration/Events/EventWidgetListSettingsTests.cs
Tests/FeatherWidgets.TestIntegration/News/NewsWidgetListSettingsTests.cs

Integration test fixes

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormViewModel.cs
Tests/FeatherWidgets.TestIntegration/Identity/LoginForm/LoginFormTests.cs

Fixing bug #186464 - Veracode issue - RedirectUrlAfterLogin should be validated

---

Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchBoxController.cs

Search widget fix

---

Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchBoxController.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/SearchBox/SearchBoxDummyHttpContext.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/SearchBox/SearchBoxDummyHttpRequest.cs
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/SearchBox/SearchBoxControllerTests.cs

Add SearchBox Widget Unit test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Widgets/WidgetDesignerScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/News/VerifyDateSelectorAnyTimeValueForNewsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/News/VerifyDateSelectorAnyTimeValueForNewsWidget.cs

Added ui test #141533 - VerifyDateSelectorAnyTimeValueForNewsWidget

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs

Bug #186464 - removing accumulation of more then one '/' in redirect url

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/Navigation/BreadcrumbWidgetTests.cs
Tests/FeatherWidgets.TestIntegration/Navigation/DummySitemapFilter.cs

Integration test for breadcrumb fix

---

Telerik.Sitefinity.Frontend.Events/client-components/sf-events-date-filter-selector.js
Tests/FeatherWidgets.TestUI.TestCases/app.config

Fix #141533 Feather: When select 'Any time' in Date selector - the selected option is not saved in Events widget

---

Tests/FeatherWidgets.TestUI.TestCases/DocumentsList/FilterDocumentsWithCategoryTagAndDateOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/FilterDynamicItemWithCategoryTagAndDateOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/FilterImagesWithCategoryTagAndDateOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/News/FilterNewsItemWithCategoryTagAndDateOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/News/SelectCustomDateInNewsWidgetOnPageBasedOnBootstrapTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/VideoGallery/FilterVideosWithCategoryTagAndDateOnPage.cs

Fixed ui tests for Date selector #141533

---

Tests/FeatherWidgets.TestIntegration/Identity/LoginForm/LoginFormTests.cs

Applying CategoryAttribute on the LoginFormTests

---

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogPost/IBlogPostModel.cs
Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/BlogPost/designerview-simple.js
Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Models/IDynamicContentModel.cs
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Scripts/DynamicContent/designerview-simple.js
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Events/client-components/sf-events-date-filter-selector.js
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/IUsersListModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListModel.cs
Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/UsersList/designerview-simple.js
Telerik.Sitefinity.Frontend.Lists/Mvc/Models/IListsModel.cs
Telerik.Sitefinity.Frontend.Lists/Mvc/Scripts/Lists/designerview-simple.js
Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Models/DocumentsList/IDocumentsListModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/IImageGalleryModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/IVideoGalleryModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/DocumentsList/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/VideoGallery/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Views/DocumentsList/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.News/MVC/Models/INewsModel.cs
Telerik.Sitefinity.Frontend.News/MVC/Scripts/News/designerview-simple.js
Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml
Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyUsersListModel.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DummyImageGalleryModel.cs

Any date filter selection persisted.

---

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Scripts/ContentBlock/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Document/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/DocumentsList/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Video/designerview-simple.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/VideoGallery/designerview-simple.js

Added ngSanitize to media designers

---

Tests/FeatherWidgets.TestUI.TestCases/DocumentsList/FilterDocumentsWithCategoryTagAndDateOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/FilterDynamicItemWithCategoryTagAndDateOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/FilterImagesWithCategoryTagAndDateOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/News/FilterNewsItemWithCategoryTagAndDateOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/News/SelectCustomDateInNewsWidgetOnPageBasedOnBootstrapTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/VideoGallery/FilterVideosWithCategoryTagAndDateOnPage.cs

Fixed ui tests for #141533

---

Tests/FeatherWidgets.TestUI.TestCases/News/VerifyDateSelectorAnyTimeValueForNewsWidget.cs

Fixed ui test VerifyDateSelectorAnyTimeValueForNewsWidget

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerRadioButtonIds.cs
Tests/FeatherWidgets.TestUI.TestCases/DocumentsList/SelectAllPublishedDocuments.cs
Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/SelectAllPublishedImagesWithLimitOption.cs
Tests/FeatherWidgets.TestUI.TestCases/VideoGallery/SelectAllPublishedVideos.cs

Fixed ui tests

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Identity/UsersListEditScreen.cs

Fixed VerifySelectedUsersInUsersListWithSelectedSingleUserPage

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs

MVC Form - Expected format is not taken into account

Fix for #196612

---

Tests/FeatherWidgets.TestUI.Arrangements/Packaging/StaticContent/BlogPosts/ExportEditedBlogAndBlogPostsStructure.cs
Tests/FeatherWidgets.TestUI.Arrangements/Packaging/StaticContent/Libraries/ExportEditedLibrariesModule.cs
Tests/FeatherWidgets.TestUI.Arrangements/Packaging/StaticContent/ListItems/ExportEditedListsModule.cs
Tests/FeatherWidgets.TestUI.Arrangements/Packaging/StaticContent/News/ExportEditedNewsModule.cs
Tests/FeatherWidgets.TestUI.Arrangements/Packaging/StaticContent/Pages/ExportEditedPages.cs

Fixed UI tests because of packaging feature breaking changes. @gsashev

---

Telerik.Sitefinity.Frontend.Events/InterfaceMappings.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Controllers/EventSchedulerController.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventCalendarViewModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventOccurrenceViewModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventSchedulerModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventSchedulerViewMode.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/IEventSchedulerModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/designerview-simple.js
Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/DesignerView.Simple.json
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/Detail.EventDetails.cshtml
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/List.Calendar.cshtml
Telerik.Sitefinity.Frontend.Events/Telerik.Sitefinity.Frontend.Events.csproj
Telerik.Sitefinity.Frontend.Events/packages.config
Tests/FeatherWidgets.TestIntegration/Events/EventWidgetTests.cs

Added new widget 'Calendar'

---

Telerik.Sitefinity.Frontend.SocialShare/Mvc/Controllers/SocialShareController.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/SocialShare/DummySocialShareController.cs

Fixes on unit tests for SocialShareController.cs.

---

Telerik.Sitefinity.Frontend.Events/Mvc/Controllers/EventSchedulerController.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventSchedulerModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/IEventSchedulerModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/WeekStartDay.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/designerview-simple.js
Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js
Telerik.Sitefinity.Frontend.Events/Mvc/StringResources/EventResources.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/DesignerView.Simple.cshtml
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/List.Calendar.cshtml
Telerik.Sitefinity.Frontend.Events/Telerik.Sitefinity.Frontend.Events.csproj

Added new properties for event scheduler widget

---

Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventSchedulerModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/List.Calendar.cshtml

Added support for ListCssClass, js fixes, set 'All' display mode

---

Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/List.Calendar.cshtml

Add missing brackests

---

Tests/FeatherWidgets.TestIntegration/Packaging/ImportExportDynamicStructureTests.cs

Fixed DynamicStructureTransfer_ImportDynamicModule_VerifyMvcWidgetsExist test by updating export directory name.

Fixed packaging integration test

---

Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventSchedulerModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js
Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs
Tests/FeatherWidgets.TestIntegration/Events/EventWidgetTests.cs
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj

Added integration tests, calendar list sorting, change to POST request

---

Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/Detail.EventDetails.cshtml

Update details view with latest fixes

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Widgets/WidgetCalendarScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyDefaultView_CalendarView.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyDefaultView_CalendarView.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Added ui test VerifyDefaultView_CalendarView

---

Tests/FeatherWidgets.TestIntegration/Navigation/BreadcrumbWidgetTests.cs

Fix failing test for breadcrumb virtual nodes.

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Events/EventsFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Widgets/WidgetCalendarScreen.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Events/EventsWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyAllowUserToSwitchViews_CalendarView.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyAllowUserToSwitchViews_CalendarView.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Added ui test VerifyAllowUserToSwitchViews_CalendarView

---

Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs

Added more integration tests

---

Tests/FeatherWidgets.TestIntegration/News/NewsWidgetListSettingsTests.cs

canonical urls with paging

---

Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/DeleteDraftAndPublishVersionInDetailRevisionHistoryPageOnMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/DeletePublishAndDraftVersionInRevisionHistoryOnMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/OpenRevisionHistoryFromActionMenuToTemplateBasedOnLayoutFile.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/OpenRevisionHistoryFromMvcPageTemplateEditMode.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/VerifyDeletePublishedVersionFromRevisionHistoryMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/VerifyDetailedInformationOfMvcPageTemplateRevisionHistoryVersion.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/VerifyOlderAndNewerVersionInRevisionHistoryOnMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/VerifyRevertToThisVersionInRevisionHistoryOnMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/WriteEditDeleteCancelHideNoteInDetailRevisionHistoryPageOfMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/RevisionHistory/WriteEditDeleteCancelNoteMvcPageTemplateVersionInRevisionHistoryWindow.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherTestCategories.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/DeleteDraftAndPublishVersionInDetailRevisionHistoryPageOnMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/DeletePublishAndDraftVersionInRevisionHistoryOnMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/OpenRevisionHistoryFromActionMenuToTemplateBasedOnLayoutFile.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/OpenRevisionHistoryFromMvcPageTemplateEditMode.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/VerifyDeletePublishedVersionFromRevisionHistoryMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/VerifyDetailedInformationOfMvcPageTemplateRevisionHistoryVersion.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/VerifyOlderAndNewerVersionInRevisionHistoryOnMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/VerifyRevertToThisVersionInRevisionHistoryOnMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/WriteEditDeleteCancelHideNoteInDetailRevisionHistoryPageOfMvcPageTemplate.cs
Tests/FeatherWidgets.TestUI.TestCases/RevisionHistory/WriteEditDeleteCancelNoteMvcPageTemplateVersionInRevisionHistoryWindow.cs

Added ui tests for Revision History for Page Templates

---

Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/Fields/Templates/RelatedPageInlineListField.cshtml
Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/Fields/Templates/RelatedPageSingleField.cshtml

#200957 Feather dynamic widget is not working when dynamic item has related pages

---

Tests/FeatherWidgets.TestIntegration/Taxonomies/CustomTaxonomyTests.cs
Tests/FeatherWidgets.TestIntegration/Taxonomies/FlatTaxonomyTests.cs
Tests/FeatherWidgets.TestIntegration/Taxonomies/HierarchicalTaxonomyTests.cs
Tests/FeatherWidgets.TestIntegration/TestCategories.cs

Add category for taxonomies integration tests

---

.gitignore
FxCop/Feather.ruleset

fix vs2015 build errors

---

Telerik.Sitefinity.Frontend.Events/Mvc/Controllers/EventSchedulerController.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventSchedulerControllerHelper.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventSchedulerHelper.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventCalendarViewModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventOccurrenceViewModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventSchedulerModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/EventsFilter.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/IEventSchedulerModel.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Models/EventScheduler/IEventsFilter.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/List.Calendar.cshtml
Telerik.Sitefinity.Frontend.Events/Telerik.Sitefinity.Frontend.Events.csproj
Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs

Widget changes based on security report, temporary remove all integration tests

---

Tests/FeatherWidgets.TestIntegration/Taxonomies/FlatTaxonomyTests.cs

Fix taxonomy tests

---

Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/FilterEventsByCalendar.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs

Integration test and ui test fixes

---

Tests/FeatherWidgets.TestIntegration/Taxonomies/HierarchicalTaxonomyTests.cs

Fix taxonomies integration

---

Tests/FeatherWidgets.TestIntegration/Events/EventExportsTests.cs

Fixed integration test EventGoogleExportLinkTest

---

Tests/FeatherWidgets.TestIntegration/Navigation/LanguageSelectorWidgetTests.cs

Integration test runner tool was updated. With the update there were two new languages added

fixing test

---

Tests/FeatherWidgets.TestIntegration/Navigation/LanguageSelectorWidgetTests.cs

fixing integration tests for ssl

---

Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
Telerik.Sitefinity.Frontend.Blogs/packages.config
Telerik.Sitefinity.Frontend.Card/Telerik.Sitefinity.Frontend.Card.csproj
Telerik.Sitefinity.Frontend.Card/packages.config
Telerik.Sitefinity.Frontend.Comments/Telerik.Sitefinity.Frontend.Comments.csproj
Telerik.Sitefinity.Frontend.Comments/packages.config
Telerik.Sitefinity.Frontend.ContentBlock/Telerik.Sitefinity.Frontend.ContentBlock.csproj
Telerik.Sitefinity.Frontend.ContentBlock/packages.config
Telerik.Sitefinity.Frontend.EmailCampaigns/Telerik.Sitefinity.Frontend.EmailCampaigns.csproj
Telerik.Sitefinity.Frontend.EmailCampaigns/packages.config
Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
Telerik.Sitefinity.Frontend.Identity/packages.config
Telerik.Sitefinity.Frontend.InlineClientAssets/Telerik.Sitefinity.Frontend.InlineClientAssets.csproj
Telerik.Sitefinity.Frontend.InlineClientAssets/packages.config
Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj
Telerik.Sitefinity.Frontend.Lists/packages.config
Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
Telerik.Sitefinity.Frontend.Media/packages.config
Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj
Telerik.Sitefinity.Frontend.Navigation/packages.config
Telerik.Sitefinity.Frontend.Publishing/Telerik.Sitefinity.Frontend.Publishing.csproj
Telerik.Sitefinity.Frontend.Publishing/packages.config
Telerik.Sitefinity.Frontend.Search/Telerik.Sitefinity.Frontend.Search.csproj
Telerik.Sitefinity.Frontend.Search/packages.config
Telerik.Sitefinity.Frontend.SocialShare/Telerik.Sitefinity.Frontend.SocialShare.csproj
Telerik.Sitefinity.Frontend.SocialShare/packages.config
Telerik.Sitefinity.Frontend.Taxonomies/Telerik.Sitefinity.Frontend.Taxonomies.csproj
Telerik.Sitefinity.Frontend.Taxonomies/packages.config

Asimeonov code base

---

Tests/FeatherWidgets.TestUI.TestCases/Identity/LoginFormAndLoginStatusOnTheSamePage.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/ValidateAllFieldsInRegistrationWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifyLoginWidgetToTemplateWhenOpenItemDetailViewAndForgotPassword.cs
Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SemanticUITemplate.cs

Fix 4 UI Tests

---

Tests/FeatherWidgets.TestIntegration/Identity/LoginStatus/LoginTests.cs

Added more logging info for errors in Login integration tests.

LoginTestsFix

---

Telerik.Sitefinity.Frontend.Events/Mvc/Controllers/EventSchedulerController.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventSchedulerHelper.cs
Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs

Fixed widget errors in templates, added data clear on test init

---

Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventSchedulerHelper.cs

Fixed issues with editable on pages

---

Telerik.Sitefinity.Frontend.Events/Mvc/Helpers/EventSchedulerHelper.cs

Preview is now displaying draft version

---

Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js
Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/List.Calendar.cshtml

Added fix for multisite issues on page edit mode, new attribute - curent site id

---

Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js

Fix js file

---

Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js

Suport for page editor and calendar filtering

---

Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/List.Calendar.cshtml

Removed duplicate attribute, change resource registration to not throw an exception

---

Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyHybridPageTemplatePreviewWithCalendarWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyMvcPageTemplatePreviewWithCalendarWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyHybridPageTemplatePreviewWithCalendarWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyMvcPageTemplatePreviewWithCalendarWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Adding 2 test cases for Preview of Page template with Calendar widget

---

Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyRevisionHistoryOfMVCPageTemplateContainsCalendarWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyRevisionHistoryOfPageContainsCalendarWidget.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyRevisionHistoryOfMVCPageTemplateContainsCalendarWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyRevisionHistoryOfPageContainsCalendarWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Addind 2 ui tests for Revision History on Calendar widget

---

Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs

Integration Tests for Calendar Events

---

Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
Telerik.Sitefinity.Frontend.Blogs/app.config
Telerik.Sitefinity.Frontend.Blogs/packages.config
Telerik.Sitefinity.Frontend.Card/Telerik.Sitefinity.Frontend.Card.csproj
Telerik.Sitefinity.Frontend.Card/app.config
Telerik.Sitefinity.Frontend.Card/packages.config
Telerik.Sitefinity.Frontend.Comments/Telerik.Sitefinity.Frontend.Comments.csproj
Telerik.Sitefinity.Frontend.Comments/app.config
Telerik.Sitefinity.Frontend.Comments/packages.config
Telerik.Sitefinity.Frontend.ContentBlock/Telerik.Sitefinity.Frontend.ContentBlock.csproj
Telerik.Sitefinity.Frontend.ContentBlock/app.config
Telerik.Sitefinity.Frontend.ContentBlock/packages.config
Telerik.Sitefinity.Frontend.Events/Telerik.Sitefinity.Frontend.Events.csproj
Telerik.Sitefinity.Frontend.Events/app.config
Telerik.Sitefinity.Frontend.Events/packages.config
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Telerik.Sitefinity.Frontend.Forms/app.config
Telerik.Sitefinity.Frontend.Forms/packages.config
Tests/FeatherWidgets.TestIntegration/app.config
Tests/FeatherWidgets.TestUI.Arrangements/app.config
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/app.config
Tests/FeatherWidgets.TestUnit/packages.config
Tests/FeatherWidgets.TestUtilities/app.config

@aleksandra992 
@Boyko-Karadzhov

Upgrade to Newtonsoft.Json 9.0.1

---

Tests/FeatherWidgets.TestUI.Arrangements/Events/VerifyTwoCalendarsWidgetsOnPage.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyTwoCalendarsWidgetsOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj

Adding ui test for calendar widget

---

Telerik.Sitefinity.Frontend.SocialShare/Mvc/Views/SocialShare/SocialShareIconsWithText.cshtml
Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj
Tests/Feather.Widgets.TestUI.Framework/Framework/SciptHelpers/set-dec-test-data.js
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDecTrackingWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetsFacade.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Lists/ListsWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/MediaWidgets/MediaWidgetsWrapper.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/SocialShare/SocialShareWrapper.cs
Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj
Tests/FeatherWidgets.TestUI.Arrangements/Lists/CheckIfRequestToDecIsSendOnListExpanded.cs
Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyExpandedListTemplate.cs
Tests/FeatherWidgets.TestUI.Arrangements/MediaWidgets/CheckIfRequestToDecIsSendOnVideoPlayed.cs
Tests/FeatherWidgets.TestUI.Arrangements/SocialShare/CheckIfRequestToDecIsSendOnSocialButtonClick.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Tests/FeatherWidgets.TestUI.TestCases/Lists/CheckIfRequestToDecIsSendOnListExpanded.cs
Tests/FeatherWidgets.TestUI.TestCases/MediaWidgets/CheckIfRequestToDecIsSendOnVideoPlayed.cs
Tests/FeatherWidgets.TestUI.TestCases/SocialShare/CheckIfRequestToDecIsSendOnSocialButtonClick.cs

#1964, #1968, #1969 - UI test for widgets tracking

---

Tests/FeatherWidgets.TestIntegration/Common/LayoutCompilationPerformanceTests.cs
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj

Layout compilation tests

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Form/Index.cshtml
Tests/FeatherWidgets.TestIntegration/Forms/FormEventsTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Forms/FormsOperations.cs

Fix forms multisubmit

---

Tests/FeatherWidgets.TestIntegration/Common/LayoutCompilationPerformanceTests.cs
Tests/FeatherWidgets.TestIntegration/Common/WidgetCompilationPerformanceTests.cs

Fix AutoReadOnly mode integration tests

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Form/Index.cshtml
Tests/FeatherWidgets.TestIntegration/Forms/FormEventsTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Forms/FormsOperations.cs

Fix forms refresh

---

Tests/FeatherWidgets.TestUI.TestCases/News/FilterNewsItemFromDifferentProviderWithCategoryOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/News/SelectNewsItemFromDifferentProviderInNewsWidget.cs

UI tests fixes

---

Tests/FeatherWidgets.TestIntegration/Common/LayoutCompilationPerformanceTests.cs
Tests/FeatherWidgets.TestIntegration/Common/WidgetCompilationPerformanceTests.cs
Tests/FeatherWidgets.TestIntegration/TestCategories.cs

Fix autoreadonly integration tests

---

Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs

Calendar Events integration test - stabilization

---

Tests/FeatherWidgets.TestUI.TestCases/Common/UninstallFeatherAndVerifyFormsMvcOption.cs

Added additional wait when initally navigate to modules and services

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs

Removed RelativeRouteAttribute from Index action of LoginStatusController

---

Telerik.Sitefinity.Frontend.DynamicContent/DynamicWidgetInitializer.cs
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Controllers/DynamicContentController.cs
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Models/DynamicContentModel.cs
Telerik.Sitefinity.Frontend.Taxonomies/Helpers/ContentTypeExtensions.cs

Performance improvement for dynamic content widgets, to use the cache instead of getting the data from the DB every time.

dynamic content widget performance improvement

---

Tests/FeatherWidgets.TestIntegration/Common/LayoutCompilationPerformanceTests.cs
Tests/FeatherWidgets.TestIntegration/Common/WidgetCompilationPerformanceTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Templates/TemplateOperations.cs

Diagnostics int tests

---

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Helpers/ItemViewModelExtensions.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsHierarchicalContentTests.cs

Task #205818: Add integration test for bug #205393: Feather: Cannot retrieve Parent Item Related Data from child item

Fix for bug #205393: Feather: Cannot retrieve Parent Item Related Data from child item

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs
Tests/FeatherWidgets.TestIntegration/Identity/LoginForm/LoginFormTests.cs
Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/SelectAllPublishedImagesWithLimitOption.cs
Tests/FeatherWidgets.TestUI.TestCases/Packaging/DynamicContent/ExportImportModuleAllFieldsFrontendCheck.cs
Tests/FeatherWidgets.TestUI.TestCases/Packaging/DynamicContent/ImportFlatModuleAllFields.cs
Tests/FeatherWidgets.TestUI.TestCases/Packaging/StaticContent/Libraries/ImportEditedWidgetTemplateLibrariesStructure.cs

Ignored unstable UI tests.

---

Tests/FeatherWidgets.TestIntegration/Common/DynamicWidgetCompilationPerformanceTests.cs
Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj

Added integration tests for dynamic content widget performance

---

Tests/FeatherWidgets.TestUI.Arrangements/Events/DragAndDropEventsWidgetOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/DragAndDropEventsWidgetOnPage.cs

Fix UI test DragAndDropEventsWidgetOnPage

---

Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerContentTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsDesignerListSettingsTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsHierarchicalContentTests.cs
Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsRoutingTests.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/DynamicModules/DynamicModuleModule2Operations.cs

Fixes on failing dynamic modules integration tests.

---

Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/TemplateGenerator.cs

Fix for missing dynamic widget templates after edit

---

Telerik.Sitefinity.Frontend.Events/Mvc/Views/EventScheduler/List.Calendar.cshtml

fix calendar special char issues

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Selectors/SelectorsWrapper.cs
Tests/FeatherWidgets.TestIntegration/News/NewsWidgetListSettingsTests.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/DragAndDropEventsWidgetOnPage.cs
Tests/FeatherWidgets.TestUI.Arrangements/News/SelectNewsItemFromDifferentProviderInNewsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/DragAndDropEventsWidgetOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyPagingOnFrontendPageForEventsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyUseLimitListSettingsOnFrontendPageForEventsWidget.cs
Tests/FeatherWidgets.TestUI.TestCases/News/FilterNewsItemFromDifferentProviderWithCategoryOnPage.cs
Tests/FeatherWidgets.TestUI.TestCases/News/SelectNewsItemFromDifferentProviderInNewsWidget.cs
Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/NewsOperations.cs

Fix team7 tests

---

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
Tests/FeatherWidgets.TestIntegration/packages.config

Telerik.Sitefinity.Diagnostics version updated to 10.0.6400.0

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/FormController.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Form/Form.SubmitResultView.cshtml
Telerik.Sitefinity.Frontend.Forms/Telerik.Sitefinity.Frontend.Forms.csproj
Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
Tests/FeatherWidgets.TestUnit/Forms/FormControllerTests/FormControllerTests.cs
Tests/FeatherWidgets.TestUnit/Forms/FormControllerTests/Helpers/FormControllerStub.cs
Tests/FeatherWidgets.TestUnit/Forms/FormControllerTests/Helpers/FormModelStub.cs

Added a new view for displaying of the form submit result message, instead of just returning it as content result.
Reviewers

MVC forms success/error message Action #2048

---

Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs

Fixed failed integration tests

---

Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/CreateSplitPageWithPersonalizedContentBlock.cs
Tests/FeatherWidgets.TestUI.Arrangements/Events/FilterByAllEvents.cs
Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/CreateSplitPageWithPersonalizedContentBlock.cs
Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/DuplicateCssWidgetOnPage.cs

Fix failing ui tests

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Identity/UsersListWrapper.cs

Fix for VerifySelectedRolesInUsersListOnBootstrapPage

---

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Identity/LoginStatusFrontend.cs
Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Identity/LoginStatusWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifyLoginWidgetToTemplateWhenOpenItemDetailViewAndForgotPassword.cs
Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifyLoginWidgetWhenOpenItemDetailViewAndForgotPassword.cs

Fixes for UI tests

---

Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/ChangeCommentsStatusesForPage.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/ChangeReviewsStatusesForPage.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/CommentsFrontendLoadMoreLink.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/CommentsFrontendShowOldestAndNewestOptions.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/DeleteNewsItemWithSubmittedComments.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/DisableAndEnableEmailNotificationsForPages.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/DisableCommentsForPage.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/EditCommentWidgetAndCloseCommentsForPage.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/SubmitCommentForDynamicItemLoggedUserOnBootstrapPage.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/SubmitCommentForNewsLoggedUserOnBootstrapPage.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/SubmitCommentForPageLoggedUserOnBootstrapPage.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/SubmitCommentToNewsItemThatRequireAuthentication.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/SubmitReviewsToNewsItemThatRequireAuthentication.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/SubscribeUserForCommentsNotificationAndVerifyReceivedEmail.cs
Tests/FeatherWidgets.TestUI.TestCases/CommentsAndReviews/UnsubscribeUserForCommentsNotification.cs
Tests/FeatherWidgets.TestUI.TestCases/FeatherTestCase.cs

Fixes for 15 UI test CommentsAndReviews

---

Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchResultsController.cs
Telerik.Sitefinity.Frontend.Search/Mvc/Models/SearchResultsModel.cs
Telerik.Sitefinity.Frontend.Search/Mvc/StringResources/SearchWidgetsResources.cs
Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml
Tests/FeatherWidgets.TestIntegration/SearchResults/SearchResultsWidgetTests.cs

Search results can be filtered by permissions, new integration tests

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Models/FormModel.cs
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/Form/Index.cshtml

Fixed ajax submit in wrong form

---

Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchResultsController.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/SearchResults/DummySearchResultsController.cs

Fixed failing unit tests

---

Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs

Event scheduler widget integrations tests fix for stabilization

---

Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageDetailsViewModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ThumbnailViewModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/Detail.DetailPage.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ImageGallery.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.OverlayGallery.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.SimpleList.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml

Fix for bug #207396: Feather + Web forms: Image Gallery - svg images are not shown properly

Fix for bug: Feather + Web forms: Image Gallery - svg images are not shown properly

---

Telerik.Sitefinity.Frontend.Media/Mvc/Helpers/ImageHelpers.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/Image.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/Detail.DetailPage.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ImageGallery.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.OverlayGallery.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.SimpleList.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml

Fix for bug: SVG - Image widget with Custom size is not rendered

---

Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/LinkSelector/LinkSelectorInsertAnAnchor.cs
Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelector/LinkSelectorInsertAnAnchor.cs

paragraph is moved inside div tag

fixed ui test LinkSelectorInsertAnAnchor

---

Telerik.Sitefinity.Frontend.Events/Mvc/Scripts/EventScheduler/scheduler-events.js
Tests/FeatherWidgets.TestUI.TestCases/Events/VerifyRecurrentAllDayEventFiveRepeats_CalendarView.cs

#211940 MVC Calendar widget - Agenda view is not displaying all day events properly

---

Telerik.Sitefinity.Frontend.Media/Mvc/Helpers/ImageHelpers.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ThumbnailViewModel.cs
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/overlay-gallery.js
Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/thumbnail-strip.js
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/Detail.DetailPage.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ImageGallery.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.OverlayGallery.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.SimpleList.cshtml
Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml

Fix for bug #212206: SVG images are not displayed properly in Image Gallery Overlay/Thumbain Strip

Fix bug: SVG images are not displayed properly in Image Gallery Overlay/Thumbain Strip

---

Tests/FeatherWidgets.TestUI.Arrangements/CommentsAndReviews/SubmitCommentToNewsItemThatRequireAuthentication.cs

Fix UI test SubmitCommentToNewsItemThatRequireAuthentication

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendCommonWrapper.cs
Tests/FeatherWidgets.TestUI.TestCases/Common/DeactivateFeatherModule.cs

Fix DeactivateFeatherModule UI test

---

Telerik.Sitefinity.Frontend.Media/Mvc/Helpers/ImageHelpers.cs

#207248 - Image widget fix

---

Tests/FeatherWidgets.TestIntegration/Events/EventSchedulerWidgetTests.cs

Calendar widget integration tests fix for case when a leap year is a previous or next year

---

Tests/FeatherWidgets.TestIntegration/SearchResults/SearchResultsWidgetTests.cs

Delete all search indexes, instead of deleting created index in the test

---

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs

Media UI tests fix

---

Telerik.Sitefinity.Frontend.EmailCampaigns/Mvc/Controllers/UnsubscribeFormController.cs
Telerik.Sitefinity.Frontend.EmailCampaigns/Mvc/Models/UnsubscribeForm/IUnsubscribeFormModel.cs
Telerik.Sitefinity.Frontend.EmailCampaigns/Mvc/Models/UnsubscribeForm/UnsubscribeFormModel.cs
Tests/FeatherWidgets.TestUnit/DummyClasses/UnsubscribeForm/DummyUnsubscribeFormModel.cs

fix #213662 Newsletters: The unsubscribe link is not resolved in a welcome email

---

Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/Write.Default.cshtml
Telerik.Sitefinity.Frontend.Forms/Mvc/Views/MultipleChoiceField/Write.Default_Inline.cshtml

Reverts Sitefinity/feather-widgets#2143

Revert "Bug fix - #198862 - Submitting a form causes an error"

---

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs
Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs
Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js
Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Controllers/DynamicContentController.cs
Telerik.Sitefinity.Frontend.Events/Mvc/Controllers/EventController.cs
Telerik.Sitefinity.Frontend.Lists/Mvc/Controllers/ListsController.cs
Telerik.Sitefinity.Frontend.Lists/Mvc/Scripts/Lists/lists.js
Telerik.Sitefinity.Frontend.News/MVC/Controllers/NewsController.cs

#214039 - Enable personalization and fixed js code for Blog, BlogPost, DynamicContent, Event, List and News widgets

---

.nuget/NuGet.targets

Update nuget package url

---

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/ChangePassword/ChangePasswordModel.cs

Method not set as virtual #1953
