Sitefinity/feather-widgets

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Scripts/DynamicContent/designerview-simple.js, Telerik.Sitefinity.Frontend.DynamicContent/Mvc/StringResources/DynamicContentResources.cs, Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml
Need to merge Feather's branch 'sorting-option' in order for this code to work
=> Closes #91

Telerik.Sitefinity.Frontend.Search/Mvc/Models/OrderByOptions.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Models/SearchResultsModel.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml
For review:
[] @GeorgiMateev 
[] @PepiIvanova
=> Removed sort by title #113

Telerik.Sitefinity.Frontend.Search/Mvc/StringResources/SearchWidgetsResources.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml
For review:
- [] @GeorgiMateev  
-  [] @PepiIvanova
=> Changed Html.DropDownList to select #124

SetupScripts/FeatherSetup.ps1, Tests/FeatherWidgets.TestIntegration/SearchResults/SearchResultsWidgetTests.cs
=> fixed failing integration tests

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Navigation/NavigationWidgetFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Navigation/NavigationWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/DeleteNavigationWidgetFromPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetAllLevelsToInclude.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetAllPagesType.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetAllPagesUnderCurrentlyOpenedPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetAllSiblingPagesOfCurrentlyOpenedPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetHorizontalTemplateWithOneLevelOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetOnSemanticTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetSitemapTemplateWithOneLevelOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetVerifyPagePermissions.cs
=> Fix ui tests for navigation

Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/NavigationController.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/NavigationModel.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Scripts/Navigation/designerview-simple.js, Telerik.Sitefinity.Frontend.Navigation/Mvc/StringResources/NavigationResources.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj, Telerik.Sitefinity.Frontend.Navigation/packages.config, Tests/FeatherWidgets.TestIntegration/Navigation/NavigationWidgetPageSelectionModeTests.cs
nav-page-selector-#150 is merged to this branch and is already deleted.
=> Nav page / multi-page selector #151 #150

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Navigation/NavigationWidgetEditWrapper.cs
=> fixed navigation wrapper - select navigation mode option

Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/DesignerView.Simple.cshtml
=> Minor UX fixes in new Navigation options

Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml
=> Added styles and markup for images and videos in search results

Telerik.Sitefinity.Frontend.ContentBlock/Telerik.Sitefinity.Frontend.ContentBlock.csproj, Telerik.Sitefinity.Frontend.DynamicContent/Telerik.Sitefinity.Frontend.DynamicContent.csproj, Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj, Telerik.Sitefinity.Frontend.News/Telerik.Sitefinity.Frontend.News.csproj, Telerik.Sitefinity.Frontend.Search/Telerik.Sitefinity.Frontend.Search.csproj, Telerik.Sitefinity.Frontend.SocialShare/Telerik.Sitefinity.Frontend.SocialShare.csproj
=> generate XML doc

Tests/FeatherWidgets.TestUnit/SearchResults/SearchResultsControllerTests.cs
=> Fixed the CallIndexAction_WithParams_EnsureTheModelIsProperlyCreated test

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Scripts/Designer/modal-dialog.js
=> link selector now works on IE and FF

Tests/FeatherWidgets.TestUtilities/Data/NewsWidget/Detail.DetailPageRelatedData.cshtml
fixed detail page template used in UI test AddRelatedDataToNewsWidget
=> fixed UI test AddRelatedDataToNewsWidget

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml
=> https://github.com/Sitefinity/feather/issues/252

Tests/FeatherWidgets.TestIntegration/SearchResults/SearchResultsWidgetTests.cs
=> search results integration tests

Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/Navigation/NavigationWidgetAllPagesUnderParticularPage.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetAllPagesUnderParticularPage.cs
Added 3 UI tests for the different templates : Bootstrap, Foundation and
SemanticUI
for review:
=> UI test NavigationWidgetAllPagesUnderParticularPage

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerContentScreenWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/ReorderSelectedDynamicItems.cs, Tests/FeatherWidgets.TestUI.TestCases/News/ReorderSelectedNewsItems.cs
=> fixed UI tests for reordering

Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/DesignerView.Simple.json
=> Fixed script dependencies#255

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockLinkSelectorScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockLinkSelectorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ContentBlock/ContentBlockWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/LinkSelectorInsertLinkToWebPageOverSelectedText.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorEditInsertedLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPageOverSelectedText.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
=> New UI test for link selector

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Views/ContentBlock/DesignerView.Simple.json
=> Added missing reference#452

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorEditInsertedLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPageOverSelectedText.cs
Updated UI tests with additional steps in order to verify the content in
content block design mode
For review:
=> Added test method VerifyContentBlockTextDesignMode

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Views/ContentBlock/DesignerView.Simple.json
=> media markup service

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/FeatherElementMap.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Search/SearchBoxWidgetEditScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Search/SearchFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Search/SearchMap.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Search/SearchResultsWidgetEditScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/BackendWrappersFacade.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Search/SearchBoxWidgetWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Search/SearchResultsWidgetWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Search/SearchWrapperFacade.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendWrappesFacade.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Search/SearchWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Search/SearchWrapperFacade.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_NonAuthenticatedUser.cs, Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_SortingOnFrontend.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherTestCategories.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/Navigation/LightNavigationAndMvcNavigation.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_NonAuthenticatedUser.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SortingOnFrontend.cs
=> Search ui tests

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Scripts/Designer/modal-dialog.js
=> added resolve options for modal dialog

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockLinkSelectorScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockLinkSelectorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/BaseWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ContentBlock/ContentBlockWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendCommonWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendWrappesFacade.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ModuleBuilder/InlineEditingWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/LinkSelectorLinkToPageFromThisSite.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorEditInsertedLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPageOverSelectedText.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorLinkToPageFromThisSite.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
Added new wrapper for common frontend operations
Edited element maps and wrappers for link selector to work for all types
of inserted link (web address, page, etc.)
For review:
=> added test LinkSelectorInsertLinkToPageFromThisSite

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Search/SearchFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Search/SearchWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_BootstrapTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_FoundationTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_SemanticUITemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_SortingOnFrontend.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_BootstrapTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_FoundationTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SemanticUITemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SortingOnFrontend.cs
=> Added search tests for package templates

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Selectors/SelectorsWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/LinkSelectorInsertLinkToPageFromThisSiteOverSelectedText.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToPageFromThisSiteOverSelectedText.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
=> Add new tests for link selector, pages option

Telerik.Sitefinity.Frontend.Navigation/Mvc/StringResources/NavigationResources.cs
=> Added ellipsis to a label in navi widget

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Views/ContentBlock/DesignerView.Simple.json
=> added thumbnail size script

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockLinkSelectorScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockLinkSelectorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/LinkSelectorInsertAnAnchor.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/LinkSelectorInsertLink.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorEditInsertedLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertAnAnchor.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToEmailAddress.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToPageFromThisSiteOverSelectedText.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorLinkToPageFromThisSite.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
=> Link selector insert link to email address

Telerik.Sitefinity.Frontend.SocialShare/Mvc/Views/SocialShare/DesignerView.Simple.cshtml
=> Fixed unnecessary whitespace in Social share widget

Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/AddContentBlockWidgetToTemplateBasedOnLayoutFile.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Templates/TemplateOperations.cs
=> fixed UI test arrangement

Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/ActivateAndDeactivateModuleBuilder.cs, Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/DynamicModuleAddNewContentTypeVerifyPageToolbox.cs
Added missing DeleteAllModules for Module Builder tests
=> fixed arrangement methods in UI tests

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/AddContentBlockToTemplateBasedOnLayoutFile.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ContentBlockWidgetOnPageBasedOnPackageTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/DeleteNavigationWidgetFromPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/LightNavigationAndMvcNavigation.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetAndContentBlockWidgetOnTheSamePage.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetHorizontalTemplateWithOneLevelOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetOnBootstrapTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetOnFoundationTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetOnSemanticTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/News/DragAndDropNewsWidgetOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/News/NavigateDetailTemplateOfNewsOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_BootstrapTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_FoundationTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_NonAuthenticatedUser.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SemanticUITemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SortingOnFrontend.cs
combine duplicated methods for adding widget in pure mvc mode
changed and renamed method for adding mvc widget in hybrid mode
for review:
=> re-factored and renamed methods for adding widget

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Scripts/Designer/modal-dialog.js
=> modal dialogs fix #698

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockLinkSelectorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ContentBlock/ContentBlockWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/LinkSelectorInsertLinkToWebPageOverSelectedImage.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertAnAnchor.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToEmailAddress.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPageOverSelectedImage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertRemoveLinkToWebPage.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
=> Link selector insert link to web page over selected image

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockLinkSelectorScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockLinkSelectorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertAnAnchor.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToEmailAddress.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/FilterDynamicItemWithCategoryOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/News/FilterNewsItemWithCategoryOnPage.cs
=> Add UI test for empty anchor tab and in two tests verifications for categories

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Search/SearchWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_NonAuthenticatedUser.cs
=> Enhancements on Search UI tests

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js
=> refactor image widget designer

Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/IImageModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/ImageModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/ImageViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/ImageResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/Image.cshtml, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Image widget

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js
=> Fixed checking of image as link on designer open#619

Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/DesignerView.Simple.cshtml
=> image widget ux fixes

Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/IImageModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/ImageModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/ImageViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/Image.cshtml
=> Removed markup

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Navigation/NavigationWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Search/SearchWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/Navigation/NavigationWidgetCustomSelectionOfPages.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetCustomSelectionOfPages.cs
- refactored method for VerifyNavigationOnThePageFrontend to verify also
the nodes order
- fixed style cop issue in SearchWrapper
For review:
Test results: https://feather-ci.sitefinity.com/job/ui-tests-navigation-custom-selection_FeatherWidgetsUITests_Navigation/1/testReport/
=> added UI test NavigationWidgetCustomSelectionOfPagesPageBootstrap

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/IImageModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/ImageModel.cs
=> Integration of ContentLocations service.

Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/Image.cshtml
=> Updated image widget template

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageController.cs
=> Fixing unexpected exception.

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/DesignerView.Simple.cshtml
=> Added footer template and added disabled props in the save btns.

Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj, Telerik.Sitefinity.Frontend.Media/packages.config
=> Dependencies to Sitefinity are fixed.

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageController.cs
=> Fixed error when image is empty

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockWidgetScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPageOverSelectedImage.cs
=> Full content mode ui test

Telerik.Sitefinity.Frontend.Media/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/IImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/ImageGalleryResources.cs, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Added controller + dummy model

Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/IImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/MediaGalleryModelBase.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/ParentFilterMode.cs, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj, Telerik.Sitefinity.Frontend.Media/packages.config
=> Img gallery model #304

FeatherWidgets.sln, Telerik.Sitefinity.Frontend.Identity/Properties/AssemblyInfo.cs, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj, Telerik.Sitefinity.Frontend.Identity/packages.config
=> Initial commit.

Tests/FeatherWidgets.TestUnit/Resources/ResourcesTests.cs
=> add image resources image tests

Telerik.Sitefinity.Frontend.Identity/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/ILoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/LoginStatusResources.cs, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj, Telerik.Sitefinity.Frontend.Identity/packages.config
=> Empty ctrl, model and view model

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Controllers/DynamicContentController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/MediaGalleryModelBase.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DummyImageGalleryController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DummyImageGalleryModel.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/Media/Image/ImageControllerTests.cs, Tests/FeatherWidgets.TestUnit/Media/ImageGallery/ImageGalleryControllerTests.cs
=> Img gallery ctrl tests #342

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs
=> Image Gallery: Integrate Controller and Model #305

Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj, Telerik.Sitefinity.Frontend.Identity/packages.config, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Added packages

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/LoginStatus/designerview-simple.js, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Included designerview.js and views and json.

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Selectors/SelectorsScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Selectors/SelectorsWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToPageFromThisSiteOverSelectedText.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/ExpandPagesInDynamicWidgetAndSelectChildPageForSingleItemPage.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/SearchInDynamicWidgetForSingleItemPageAndVerifyBreadcrumb.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetCustomSelectionOfPages.cs, Tests/FeatherWidgets.TestUI.TestCases/News/ChangeSelectedSingleItemPage.cs, Tests/FeatherWidgets.TestUI.TestCases/News/ExpandPagesAndSelectChildPageForSingleItemPage.cs, Tests/FeatherWidgets.TestUI.TestCases/News/SearchForSingleItemPageAndVerifyBreadcrumb.cs
=> New method for checking page statuses in UI tests in page selector

Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/DesignerView.Simple.cshtml
=> fixed provider selection in image widget

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/thumbnail-strip.js
=> fix client tests

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/ILoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/StatusViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Logout #794

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/DesignerView.Simple.cshtml
=> Removed disabled inputs and added check if title and alt exist.

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/SelectItemInDynamicWidgetFromDifferentProvider.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/SelectItemInDynamicWidgetFromDifferentProvider.cs, Tests/FeatherWidgets.TestUI.TestCases/Navigation/NavigationWidgetCustomSelectionOfPages.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/DynamicModules/DynamicModulePressArticleOperations.cs
- added overload methods in DynamicModulePressArticleOperations in order
to use providerName as parameter
- enhanced arrangement for UI test
- fixed some StyleCop issues
for review:
=> re-factored UI test SelectItemInDynamicWidgetFromDifferentProvider

Telerik.Sitefinity.Frontend.Media/Mvc/Models/MediaGalleryModelBase.cs
=> Fix void library #812

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginName.cshtml
=> Altered templates

Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml
=> Fixed empty thumbnail strip#361

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginButton.cshtml
=> Changed templates and page url returns null instead of string.Empty

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/IImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageDetailsViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/ImageGalleryResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailsList.cshtml
=> Implemented next and previous image links for image gallery detail template

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DummyImageGalleryController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DummyImageGalleryModel.cs, Tests/FeatherWidgets.TestUnit/Media/ImageGallery/ImageGalleryControllerTests.cs
=> Failing unit tests

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/ILoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/LoginFormResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/LoginForm.Index.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Initial commit of the LoginForm widget.

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/designerview-simple.js
=> Change provider #839

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs
=> Login page url getting fixed

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs
=> Added check for empty login redirect page

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/thumbnail-strip.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml
=> selecting images in thumbnail strip changes the URL

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/LoginStatus/designerview-simple.js
=> Refactor designer script login status

Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/IImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/MediaGalleryModelBase.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/ImageGalleryResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/DesignerView.Simple.cshtml, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DummyImageGalleryModel.cs
=> removed include child libraries

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/overlay-gallery.js, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/thumbnail-strip.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.OverlayGallery.cshtml, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> added dynamic url changing in overlay gallery

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/ILoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/LoginStatusResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/DesignerView.Simple.cshtml, Tests/FeatherWidgets.TestIntegration/Identity/LoginStatus/LoginTests.cs
=>  Implement the Windows STS option #836

Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/MediaGalleryModelBase.cs
=> image gallery uses thumbnails by default

Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml
=> Added default data back to thumbnail strip

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/overlay-gallery.js, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/thumbnail-strip.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.OverlayGallery.cshtml
=> thumbnail dynamic url fixes

Telerik.Sitefinity.Frontend.Media/Mvc/Models/MediaGalleryModelBase.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/designerview-simple.js
Fixed bugs: https://github.com/Sitefinity/feather/issues/726, https://github.com/Sitefinity/feather/issues/812
=> Image gallery library selector fixes

Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/ImageSizeModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/ThumbnailModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs
=> Default thumb size #401

Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml
=> Added prev and next links text

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/LoginStatus/login-status.js, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginButton.cshtml
=> Login redirects ml#866

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginName.cshtml
=> logout button in login name template is now a link

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ChangePasswordController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/ChangePassword/ChangePasswordInputModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/ChangePassword/ChangePasswordModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/ChangePassword/ChangePasswordViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/ChangePassword/IChangePasswordModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/ILoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/ResetPasswordInputModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/ChangePasswordResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/LoginFormResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/ChangePassword/ChangePassword.Default.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Change password index action #882

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/IRegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/ProfileBindingsContract.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/ProfileBindingsModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/ProfileBindings.json, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Register user #421

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/IRegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Registration/designerview-simple.js, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/RegistrationResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
https://github.com/Sitefinity/feather-widgets/issues/413
=> Integrating role selector #413

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/LoginStatus/login-status.js
=> not able to logout when using STS authentication mode #858

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ChangePasswordController.cs
=> Moved redirect after change password to happen in post action (sooner).

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml
=> form helpers for registration form

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Success email registration

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/LoginForm.Default.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml
=> Impl reg form #432

Telerik.Sitefinity.Frontend.Identity/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ProfileController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/IProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/ProfileResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Profile.ProfilePreview.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Added profile widget

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/AccountActivation/AccountActivationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/AccountActivation/IAccountActivationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/AccountActivationResources.cs
=> Account activation #444

Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/NavigationModel.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/SelectedPageModel.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Scripts/Navigation/designerview-simple.js
=> reorder external pages fix

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/IRegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs
=> get error method added to the registration model

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/DesignerView.Simple.cshtml
=> Fix for #465 - selected registration page is not persisted

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/NavigationController.cs, Telerik.Sitefinity.Frontend.News/MVC/Controllers/NewsController.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchBoxController.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchResultsController.cs, Telerik.Sitefinity.Frontend.SocialShare/Mvc/Controllers/SocialShareController.cs
In pure MVC mode the backend widgets are all missing their toolbox icons
=> Add in the CssClass attribute for the page designer

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyRegistrationController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyRegistrationModel.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/Identity/RegistrationControllerTests.cs
=> added registration controller unit tests

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/IRegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyRegistrationModel.cs
=> Profile bindings property

Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyAccountActivationController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyAccountActivationModel.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/Identity/AccountActivationControllerTests.cs, Tests/FeatherWidgets.TestUnit/TestInterfaceMappings.cs
=> AcountActivationController tests added

Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyRegistrationModel.cs, Tests/FeatherWidgets.TestUnit/Identity/RegistrationControllerTests.cs
=> Fixed test failing because of removed property from Registration model

Tests/FeatherWidgets.TestUnit/Identity/AccountActivationControllerTests.cs
=> Renamed exprected default view name account activation ctrl

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/IProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyProfileModel.cs, Tests/FeatherWidgets.TestUnit/Identity/ProfileControllerTests.cs
=> Success message fix#487

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageController.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchBoxController.cs
=> Fixed empty widget css

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/LoginStatus/login-status.js, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/LoginStatusResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginButton.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginName.cshtml
=> Link is now button which redirects

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/AccountActivationController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ChangePasswordController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ProfileController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs
=> Added widget icons for Zone Editor

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs
=> Added security checks supress

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/AccountActivation/AccountActivationModel.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyAccountActivationModel.cs, Tests/FeatherWidgets.TestUnit/Identity/AccountActivationControllerTests.cs
=> Fixed in logic in account activation

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Profile/designerview-simple.js, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/DesignerView.Simple.cshtml
=> Fixed - Profile: opening designer throws js error #494

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ProfileController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/IProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileEditViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyProfileModel.cs
=> Profile save fix #490

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs
=> User activation fix #933

Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/LoginFormResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/ChangePassword/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/DesignerView.Simple.cshtml
=> Changes to Login Form and Login status designers

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml
=> fixed validation messages in registration form

Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/ProfileResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/DesignerView.Simple.cshtml
=> Login widgets peleva

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj
https://github.com/Sitefinity/feather/issues/919
Changes in Sitefinity: shelveset TELERIK\npetrova -> SendSuccessfulRegistrationEmail refactoring
=> Send successful registration email refactoring

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs
=> handle login rejections

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs
=> Checks for design mode and inline edit mode

Telerik.Sitefinity.Frontend.ContentBlock/Telerik.Sitefinity.Frontend.ContentBlock.csproj, Telerik.Sitefinity.Frontend.ContentBlock/packages.config, Telerik.Sitefinity.Frontend.DynamicContent/Telerik.Sitefinity.Frontend.DynamicContent.csproj, Telerik.Sitefinity.Frontend.DynamicContent/packages.config, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/ILoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj, Telerik.Sitefinity.Frontend.Identity/packages.config, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj, Telerik.Sitefinity.Frontend.Media/packages.config, Telerik.Sitefinity.Frontend.Navigation/Telerik.Sitefinity.Frontend.Navigation.csproj, Telerik.Sitefinity.Frontend.Navigation/packages.config, Telerik.Sitefinity.Frontend.News/Telerik.Sitefinity.Frontend.News.csproj, Telerik.Sitefinity.Frontend.News/packages.config, Telerik.Sitefinity.Frontend.Search/Telerik.Sitefinity.Frontend.Search.csproj, Telerik.Sitefinity.Frontend.Search/packages.config, Telerik.Sitefinity.Frontend.SocialShare/Telerik.Sitefinity.Frontend.SocialShare.csproj, Telerik.Sitefinity.Frontend.SocialShare/packages.config, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockWidgetScreen.cs, Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj, Tests/FeatherWidgets.TestIntegration/app.config, Tests/FeatherWidgets.TestIntegration/packages.config, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/packages.config, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/packages.config, Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj, Tests/FeatherWidgets.TestUtilities/packages.config
=> Login sf refactoring

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml
=> Show password box instead plain text box

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml
=> Profile edit #904 #906

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/IRegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Registration/registration-form.js, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/RegistrationResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Add email activation template

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Read.ProfilePreview.cshtml
=> Fixed - Profile edit link is now visible when in both mode

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/DesignerView.Simple.cshtml
=> image gallery FF specifics

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs
=> profile images go in an album in the system library provider

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/LoginForm.LoginForm.cshtml
=> Fixed login form template

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml
=> added usage of data-sf-role instead class jquery selector

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Scripts/ContentBlock/shared-content-services.js, Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Scripts/DynamicContent/designerview-simple.js, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/Fields/Scripts/address-field.js, Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Registration/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/thumbnail-strip.js, Telerik.Sitefinity.Frontend.Navigation/Mvc/Scripts/Navigation/designerview-simple.js, Telerik.Sitefinity.Frontend.News/MVC/Scripts/News/designerview-simple.js, Telerik.Sitefinity.Frontend.SocialShare/Mvc/Scripts/SocialShare/designerview-simple.js
=> Fixed json parse issue with latest jQuery

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/RegistrationStaticResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> localized registration form

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/LoginStatus/login-status.js, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginButton.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginName.cshtml
=> Login status data sf role closes #526 

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs
https://github.com/Sitefinity/feather/issues/950
=> Login form wont login

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/LoginFormStaticResources.cs, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> localize login form

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml
=> Fix profile editing #956

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfilePreviewViewModel.cs
=> Fix avatar preview

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs
=> Login - correct loading of view model in case of invalid submit

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/ILoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs
=> login form settings respect provider

ReferenceAssemblies/Telerik.Sitefinity.Frontend.XML, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ProfileController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/IProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileBindingsContract.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileEditViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/ProfileResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyProfileModel.cs
=> Profile edit validation

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Registration/registration-form.js, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml
=> Registration #545

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfilePreviewViewModel.cs
=> fixed avatar caching issues

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Search/SearchBoxWidgetWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Search/SearchResultsWidgetWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Search/SearchWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/Search/VerifySearchResults_SortingOnFrontend.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_ApplyCssClass.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_BootstrapTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_FoundationTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_NonAuthenticatedUser.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SemanticUITemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Search/VerifySearchResults_SortingOnFrontend.cs
=> Refactoring - verify results page url

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/ImageGallery/designerview-simple.js
=> Fixed the broken page preview with image gallery

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/ForgotPassword.ForgottenPassword.cshtml
=> Forgot password fix#961

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs
=> workaround issue with app path

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs
=> damage control

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginStatus/LoginStatusModel.cs
=> Default logout url#972

Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/EditDynamicWidgetViaInlineEditing.cs
=> fix failinf test for dynamic widget and inline editing

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml
=> fixed registration template

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/ILoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs
=> Moved business logic outsite of the login form controller.

Telerik.Sitefinity.Frontend.Media/Mvc/Models/ImageGallery/ImageGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/Detail.DetailPage.cshtml
=> Img gallery details fix #546

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs
=> Profile - correct image upload on profile widget

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/ForgotPasswordViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/LoginFormResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/ForgotPassword.ForgottenPassword.cshtml
=> Fixed the labels and warnings in the forgot password view

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/ProfileResources.cs
=> Added validation for password length in validate model method.

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/DesignerView.Simple.cshtml
=> Added form-group class to fix indentation

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/ILoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs
=> fixed self logout regression #896

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/ResetPassword.ResetPassword.cshtml
=> Reset password#961

Telerik.Sitefinity.Frontend.Media/Mvc/Views/Image/DesignerView.Simple.cshtml
=> Added auto open selector property to image field in image designer view

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/AccountActivation/AccountActivationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/ChangePassword/ChangePasswordModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs
=> fixed issues with identity widgets on page templates

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs
=> fixing profile validation for custom fields

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Media/ImageSelectorScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/ImageSelectorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendCommonWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/ImageSelector/CheckNavigationInImageSelector.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/CheckNavigationInImageSelector.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/InsertImageFromAlreadyUploaded.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToWebPageOverSelectedImage.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/app.config
=> Insert image from specific folder

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/ImageSelectorWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/CheckNavigationInImageSelector.cs
=> Correct UI test

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Media/ImagePropertiesScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/ImagePropertiesWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/ImageSelector/EditAndChangeSelectedImage.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/EditAndChangeSelectedImage.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
=> Add new UI test for EditAndChangeSelectedImage

Gruntfile.js, Tests/FeatherWidgets.ClientTest/config/karma.conf.js
=> fixed client tests

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Profile/profile-edit.js
=> Fixed js lint issue

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/ChangePassword/ChangePassword.ChangePassword.cshtml
https://github.com/Sitefinity/feather/issues/1008
=> Fixed bug 1008: Change password widget does not work on hybrid page

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Content/ContentBlockWidgetScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Widgets/WidgetDesignerScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ContentBlockWidgetMultipleProviders.cs
Removed redundant methods from content block wrapper
For review:
=> fixed UI tests for provider selector

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Media/ImagePropertiesScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Media/ImageSelectorScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/ImagePropertiesWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/ImageSelectorWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/EditAllPropertiesOfSelectedImageAndSearch.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
=> Add test for Edit all properties and search in image selector

Telerik.Sitefinity.Frontend.Media/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/DocumentController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Document/DocumentModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Document/DocumentViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Document/IDocumentModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/DocumentResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Document/DocumentLink.cshtml, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Document widget

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Document/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/DocumentResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Document/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Document/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Added designer for the document link widget

Telerik.Sitefinity.Frontend.Media/Mvc/Models/Document/DocumentModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Document/DocumentViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Document/DocumentLink.cshtml
=> Document view fix

Telerik.Sitefinity.Frontend.Media/Mvc/Models/Document/DocumentModel.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/Document/DummyDocumentController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/Document/DummyDocumentModel.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/Media/Document/DocumentControllerTests.cs
=> Document unit tests

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/DocumentsListController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/DocumentsList/DocumentsListModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/DocumentsList/DocumentsListViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/DocumentsList/designerview-simple.js
=> Fixes - filter by taxonomies

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Media/ImagePropertiesScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/ImagePropertiesWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendCommonWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/ImageSelector/VerifyAlignmentAndImageThumbnail.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/InsertImageFromAlreadyUploaded.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/UploadImageWithCategoryAndTag.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/VerifyAlignmentAndImageThumbnail.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
=> VerifyAlignmentAndImageThumbnail ui test is added

Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DocumentsList/DummyDocument.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DocumentsList/DummyDocumentsListController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Media/DocumentsList/DummyDocumentsListModel.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/Media/DocumentsList/DocumentControllerTests.cs, Tests/FeatherWidgets.TestUnit/TestInterfaceMappings.cs
=> DocumentsListController tests added

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs
=> updated Content Block title

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ImageGallery/ImageGalleryRadioButtonIds.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ImageGallery/ImageGalleryWidgetWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ImageGallery/ImageGalleryWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/ImageGallery/SelectImagesFromSelectedLibraryInSelectedPage.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/SelectAllPublishedImagesWithLimitOption.cs, Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/SelectImagesFromSelectedLibraryInSelectedPage.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs, Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj
=> Image gallery select from specific library test

Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/ImageSelector/UploadImageWithCategoryAndTag.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/ImageGallery/FilterImagesWithCategoryTagAndDateOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/ImageSelector/UploadImageWithCategoryAndTag.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/FilterImagesWithCategoryTagAndDateOnPage.cs
=> Add new test for image gallery

FeatherWidgets.sln, Telerik.Sitefinity.Frontend.Lists/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Controllers/ListsController.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Models/IListsModel.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Models/ListsModel.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Scripts/Lists/designerview-simple.js, Telerik.Sitefinity.Frontend.Lists/Mvc/StringResources/ListsResources.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Lists/Properties/AssemblyInfo.cs, Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj, Telerik.Sitefinity.Frontend.Lists/packages.config
=> Added lists widget empty project

Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/NavigationController.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/NavigationModel.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/SelectedPageModel.cs
=> Fixed Navigation RedirectPage Issue#1073

ReferenceAssemblies/Telerik.Sitefinity.Frontend.XML, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml
=> Email validation #588

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/ImageGallery/ImageGalleryWidgetEditScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ImageGallery/ImageGalleryWidgetWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ImageGallery/ImageGalleryWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/ImageGallery/SelectSortedImagesWithChangedThumbnails.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/ImageGallery/SelectSortedImagesWithChangedThumbnails.cs
=> Add new test for image gallery, sorting and thumbnails

Telerik.Sitefinity.Frontend.Lists/Mvc/Models/ListItemsViewModel.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Models/ListsModel.cs
=> Added proper filtering for list in list widget

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/LoginForm/LoginFormModel.cs, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> login now works in Cassini

Telerik.Sitefinity.Frontend.Lists/Mvc/Models/IListsModel.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.PageList.cshtml, Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj
https://github.com/Sitefinity/feather-widgets/issues/646
=> Added page list template #646

Telerik.Sitefinity.Frontend.Lists/Mvc/Scripts/Lists/lists.js, Telerik.Sitefinity.Frontend.Lists/Mvc/StringResources/ListsWidgetResources.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.ExpandableList.cshtml, Telerik.Sitefinity.Frontend.Lists/Telerik.Sitefinity.Frontend.Lists.csproj
https://github.com/Sitefinity/feather-widgets/issues/644
=> Expandable list template #644

Telerik.Sitefinity.Frontend.Lists/Mvc/Controllers/ListsController.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Models/ListsModel.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.PagesList.cshtml
- https://github.com/Sitefinity/feather/issues/1209; 
- Implement inline editing capability into List.PagesList template;
- ListsController now implements IContentLocatableView;
=> Lists inline editing #1209

Telerik.Sitefinity.Frontend.Media/Mvc/Models/DocumentsList/DocumentDetailsViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/DocumentsList/DocumentItemViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/DocumentsList/DocumentsListModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/DocumentsList/Detail.DocumentDetails.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/DocumentsList/List.DocumentsList.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/DocumentsList/List.DocumentsTable.cshtml, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> fixed(#1214) DocumentsList: remove dot from document extension

Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.AnchorList.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.ExpandableList.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.SimpleList.cshtml
=> List widget styling

Telerik.Sitefinity.Frontend.Lists/Mvc/Models/ListItemModel.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Models/ListsModel.cs
https://github.com/Sitefinity/feather/issues/1220
=> Content location service fix

Telerik.Sitefinity.Frontend.Lists/Mvc/Controllers/ListsController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Lists/DummyDocumentsListController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Lists/DummyListsModel.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/Lists/ListsControllerTests.cs, Tests/FeatherWidgets.TestUnit/TestInterfaceMappings.cs
=> ListController unit tests added

Telerik.Sitefinity.Frontend.Media/Mvc/Views/Document/DocumentLink.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/DocumentsList/Detail.DocumentDetails.cshtml
=> Swaped doc extension and doc size position

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml
=> Document list styling

Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml
Reverts Sitefinity/feather-widgets#696
=> Revert "Document list styling"

Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchResultsController.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml
=> Search results sorting

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/LoginStatus/login-status.js, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/DocumentSelector/CheckNavigationInDocumentSelector.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/DocumentSelector/InsertDocumentFromAlreadyUploaded.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/DocumentSelector/UploadDocumentWithCategoryAndTag.cs
...en page caching is disabled
Added "cache:false" in the ajax call.
=> Login status cache

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Media/MediaPropertiesBaseScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Media/MediaSelectorScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/DocumentPropertiesWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/MediaPropertiesBaseWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/MediaSelectorBaseWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendCommonWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/ContentBlocks/DocumentSelector/EditAndChangeSelectedDocument.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/MediaWidgets/DocumentWidgetInsertDocument.cs, Tests/FeatherWidgets.TestUI.Arrangements/MediaWidgets/ImageWidgetInsertImageWithCustomThumbnail.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/DocumentSelector/EditAllPropertiesOfSelectedDocumentAndSearch.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/DocumentSelector/EditAndChangeSelectedDocument.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/MediaWidgets/DocumentWidgetInsertDocument.cs, Tests/FeatherWidgets.TestUI.TestCases/MediaWidgets/ImageWidgetInsertImageWithCustomThumbnail.cs
=> Change doc and edit all properties tests

Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/NavigationModel.cs
=> Selected pages mode now uses levels to include

Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/Profile/profile-edit.js
=> profile edit script issues

Telerik.Sitefinity.Frontend.Media/Mvc/Views/Video/Video.cshtml
=> Added markup for displaying video with auto size

ReferenceAssemblies/Telerik.Sitefinity.Frontend.XML, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/DocumentController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Helpers/MediaContentLocationHelper.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Document/DocumentModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Image/ImageModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Video/IVideoModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Video/VideoModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Video/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Integration with ContentLocations service.

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/VideoResources.cs
=> Change resource content in design mode

Telerik.Sitefinity.Frontend.Media/Mvc/Models/Video/VideoModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/Video/VideoViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Video/Video.cshtml
=> Added title and description in the Video view.

Telerik.Sitefinity.Frontend.Media/Mvc/Views/Video/Video.cshtml
=> Fixed video widget frontend

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Views/ContentBlock/DesignerView.Simple.json
=> shared content services dep moved to json

Telerik.Sitefinity.Frontend.Media/Mvc/Views/Video/Video.cshtml
=> Added closing tag for video

ReferenceAssemblies/Telerik.Sitefinity.Frontend.XML, Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/Fields/Templates/AddressField.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/DocumentsList/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml
=> Script refactor

ReferenceAssemblies/Telerik.Sitefinity.Frontend.XML, Telerik.Sitefinity.Frontend.DynamicContent/Mvc/Views/DynamicContent/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/ContainerTemplates/ListTemplateContainer.cshtml, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/Fields/Templates/AddressField.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/LoginForm.LoginForm.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginButton.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginStatus/LoginStatus.LoginName.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.ExpandableList.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/DocumentsList/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ImageGallery.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.OverlayGallery.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.SimpleList.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/ImageGallery/List.ThumbnailStrip.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/Dropdown.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Horizontal.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Sitemap.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Tabs.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Vertical.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/List.NewsList.cshtml, Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchBox/SearchBox.cshtml, Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml, Telerik.Sitefinity.Frontend.SocialShare/Mvc/Views/SocialShare/SocialShare.cshtml, Telerik.Sitefinity.Frontend.SocialShare/Mvc/Views/SocialShare/SocialShareIconsWithText.cshtml, Tests/FeatherWidgets.TestUtilities/Data/DynamicModules/List.PressArticleNew.cshtml
=> resoruces are now added to sections if available

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/VideoResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Video/Video.cshtml
=> Video page preview #1321

Telerik.Sitefinity.Frontend.Media/Mvc/Models/Video/VideoModel.cs
=> Fixed deleted video

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoController.cs
=> Fixed video delete message in design mode

Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml
=> Fixed sorting of search results widget

Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/Fields/Scripts/address-field.js
=> Fixed "View map " for address fields

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/VideoGallery/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/VideoGalleryResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Video gallery content #1293

Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/IVideoGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoThumbnailViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/VideoGallery/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/VideoGalleryResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Video gallery list settings

Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoGalleryModel.cs
=> Fixed saving of thumbnail size model

Telerik.Sitefinity.Frontend.Blogs/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/IBlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Properties/AssemblyInfo.cs, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj, Telerik.Sitefinity.Frontend.Blogs/packages.config
=> Blog posts model

Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Video/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/Video/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.cshtml
=> Refactored Video widget

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> added resources file

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/IBlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/ParentFilterMode.cs, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Added master detail functionality

Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/IVideoGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoSizeViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoThumbnailViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/VideoGallery/designerview-simple.js, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> Video gallery thumbnail size

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/List.BlogPostList.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Added list and detail views for blog post widget

Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.cshtml
=> Thumb size accepts type #1386

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoGalleryController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/DesignerView.Simple.cshtml
=> Added missing actions- ListByTaxon and Succesors

Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/BlogPost/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Blog post designer tabs

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
=> Added paging settings for blog posts widget

Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/BlogPost/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Blog post sort options

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
=> Added list template dropdown

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
=> More options blog post list

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
=> Added Open single item in ... option in blog post designer

Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/BlogPost/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Blog posts selected #1369

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
=> All posts #1368

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
=> Added detail template dropdown for blog post designer

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/IBlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/BlogPost/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj, Telerik.Sitefinity.Frontend.Blogs/packages.config
=> From selected blog

Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoGalleryController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoDetailsViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoGalleryModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Models/VideoGallery/VideoSizeViewModel.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Views/VideoGallery/Detail.Default.cshtml, Telerik.Sitefinity.Frontend.Media/Telerik.Sitefinity.Frontend.Media.csproj
=> aspect ratio affects video markup

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/IBlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/Blog/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/List.BlogList.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Blog widget scaffolding

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs
=> Integrated output cache in blog post widget

Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/BlogPost/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
=> Posts from opened blog #1396

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.json
=> Integrate blog selector

Telerik.Sitefinity.Frontend.Blogs/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/IBlogModel.cs
=> Added Blog model

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogPostResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogResources.cs, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Added class for Blog widget string resources

Telerik.Sitefinity.Frontend.Blogs/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/IBlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogPost/BlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogPost/IBlogPostModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/BlogPost/ParentFilterMode.cs, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Changed blog models namespaces

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/FeatherElementMap.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/AnchorListFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/ExpandableListFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/ExpandedListFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/ListsMap.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/SimpleListFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Lists/ListsWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/Lists/AnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/ExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/ExpandedListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/Lists/AnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/ExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/ExpandedListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/SimpleListTemplate.cs
=> Added ui tests for list templates

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs
=> Added master detail functionality for blog widget

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/List.BlogList.cshtml
=> Blogs list view impl

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/Blog/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Add blog designer tabs

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/ListsMap.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/PagesListFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Lists/ListsWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/Lists/PagesListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/Lists/PagesListTemplate.cs
=> Added ui test for page template

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/IBlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml
=> From all blogs

Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/ContainerTemplates/DetailTemplateContainer.cshtml, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/ContainerTemplates/ListTemplateContainer.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml
=> Removed Bootstrap classes from empty templates

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/IBlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/List.BlogList.cshtml
=> Blog paging settings

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/IBlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/Blog/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/List.BlogList.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Blog designer list settings

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml
=> Blog single template name

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml
=> Blog moreoptions singe item

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/IBlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/Blog/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.json
=> Selected blogs

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Helpers/DetailLocationHyperLinkHelper.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogDetailLocationMode.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/Blog/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/List.BlogList.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Open single item op

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/IBlogModel.cs
=> Added Output cache for blogs

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml
=> Added provider selector in blog widget designer

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/FilteredSelectionMode.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/IBlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Scripts/Blog/designerview-simple.js, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Display blogs that n

Telerik.Sitefinity.Frontend.Blogs/Mvc/Helpers/BlogPostHelper.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/List.BlogList.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Blog post frontend info

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs
=> Changed blog widget title

Telerik.Sitefinity.Frontend.Blogs/Mvc/StringResources/BlogListResources.cs
=> Renamed designer view resource label

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/ListsWidgetEditScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Lists/ListsWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/ExpandedListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/PagesListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/AnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/ExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/ExpandedListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/PagesListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/SimpleListTemplate.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/ListsOperations.cs
=> Lists ui test enchancements

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogModel.cs
=> Removed ILifecycleDataItemGeneric filter from expression setting

Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/DesignerView.Simple.cshtml
=> Fixed open in selected page

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogDetailsViewModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogModel.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/Blog/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Blogs/Telerik.Sitefinity.Frontend.Blogs.csproj
=> Post populating of blogs count added

Telerik.Sitefinity.Frontend.Blogs/Mvc/Helpers/BlogPostHelper.cs
=> Blog permissions #1455

Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/DesignerView.Simple.cshtml
=> Fixed hiding of narrow by when selection of blog post  is used

Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/AccountActivationResources.cs, Telerik.Sitefinity.Frontend.Media/Mvc/StringResources/DocumentsListResources.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/Resources/ResourcesTests.cs
=> Added tests for widget string resources

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Search/SearchFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/MediaPropertiesBaseWrapper.cs
=> Fix search tests and style cop errors

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs
=> Posts title #1461

Telerik.Sitefinity.Frontend.Blogs/Mvc/Models/Blog/BlogModel.cs
=> Fixed blog post count in ML

Telerik.Sitefinity.Frontend.News/MVC/Controllers/NewsController.cs
=> Added mvcWidget class to widget

Telerik.Sitefinity.Frontend.InlineClientAssets/Properties/AssemblyInfo.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Telerik.Sitefinity.Frontend.InlineClientAssets.csproj
=> added shared asm info

Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogController.cs, Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs, Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/AccountActivationController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ChangePasswordController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginFormController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/LoginStatusController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/ProfileController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/UsersListController.cs, Telerik.Sitefinity.Frontend.Lists/Mvc/Controllers/ListsController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/DocumentController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/DocumentsListController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/ImageGalleryController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoController.cs, Telerik.Sitefinity.Frontend.Media/Mvc/Controllers/VideoGalleryController.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/NavigationController.cs, Telerik.Sitefinity.Frontend.News/MVC/Controllers/NewsController.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchBoxController.cs, Telerik.Sitefinity.Frontend.Search/Mvc/Controllers/SearchResultsController.cs, Telerik.Sitefinity.Frontend.SocialShare/Mvc/Controllers/SocialShareController.cs
=> Added new icn css to all controllers

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/SitefinityProfileItemViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/List.UsersList.cshtml, Telerik.Sitefinity.Frontend.Identity/Telerik.Sitefinity.Frontend.Identity.csproj
=> Users list: Add List template

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Scripts/UsersList/designerview-simple.js, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/UsersListResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/DesignerView.Simple.cshtml
=> Users list designer fixes

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs
=> enhanced method for getting Mvc widget from the toolbox section

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/StyleSheet/StyleSheetModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Scripts/StyleSheet/designerview-simple.js, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.json
=> Media type #1484

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Scripts/StyleSheet/designerview-simple.js, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/StringResources/StyleSheetResources.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.json
=> Css code area

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/UsersListController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/IUsersListModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UserDetailsViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/UsersListResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/Detail.UserDetails.cshtml
=> User list detail view

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/List.UsersList.cshtml
=> Changes markup of Users list template

Tests/FeatherWidgets.TestUI.Arrangements/Lists/AnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/ExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/SimpleListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/AnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/ExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/ExpandedListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/PagesListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/SimpleListTemplate.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/ListsOperations.cs
=> Lists enhancements

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/StyleSheetController.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/StyleSheet/IStyleSheetModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/StyleSheet/StyleSheetModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/StringResources/StyleSheetResources.cs
=> Different css design views

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/IUsersListModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UserDetailsViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/UsersListResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/Detail.UserDetails.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/List.UsersList.cshtml
=> Added support for additional user profile

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockLinkSelectorWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/AnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/ExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/ExpandedListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/PagesListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/SimpleListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/SimpleListTemplate.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/ListsOperations.cs
=> Added filter list items by date

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/JavaScript/JavaScriptModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/JavaScript/JavaScriptViewModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/JavaScript/Index.cshtml
=> Js summary

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/JavaScript/IJavaScriptModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/JavaScript/JavaScriptModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/JavaScript/DesignerView.Simple.cshtml
=> Renamed the CustomCode property to InlineCode in the JavaScriptModel

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/List.UsersList.cshtml
=> Fix for #875 - removed the inline attributes from the users list view

Telerik.Sitefinity.Frontend.DynamicContent/MvcWidgetInstaller.cs
=> Changed title and cssClass of the dynamic widgets in toolbox

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListModel.cs
=> Limit paging error

Telerik.Sitefinity.Frontend.Identity/Mvc/Models/UsersList/UsersListModel.cs
https://github.com/Sitefinity/feather-widgets/issues/877
=> Users list fix #877

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/List.UsersList.cshtml
bootstrap template updated
https://github.com/Sitefinity/feather-packages/commit/f11ad172adb911d1523679c2509d46f5c36ab9ad
=> DIsplay user first/last name in case of custom user profile is selected

Telerik.Sitefinity.Frontend.ContentBlock/Mvc/Controllers/ContentBlockController.cs
=> Content block title

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/ExpandPagesInDynamicWidgetAndSelectChildPageForSingleItemPage.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/InvalidateCacheWhenAddNewItem.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/SearchInDynamicWidgetForSingleItemPageAndVerifyBreadcrumb.cs
- changed AddWidgetToPlaceHolderPureMvcMode method to use GetMvcWidget,
instead of GetWidgetByName
- GetWidgetByName is removed
=> fixed UI tests for dynamic widgets

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/UsersListController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyUsersListController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/Identity/DummyUsersListModel.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/Identity/UsersListControllerTests.cs, Tests/FeatherWidgets.TestUnit/TestInterfaceMappings.cs
=> User list controller unit tests

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/FeatherWidgets.TestIntegration/DynamicWidgets/DynamicWidgetsToolboxTests.cs, Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/DeactivateDynamicModuleVerifyPageToolbox.cs, Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/DynamicModuleAddNewContentTypeVerifyPageToolbox.cs, Tests/FeatherWidgets.TestUI.Arrangements/DynamicWidgets/DynamicModuleRemoveContentTypeVerifyPageToolbox.cs, Tests/FeatherWidgets.TestUI.TestCases/DynamicWidgets/DynamicWidgetsToolboxTests.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs
fixed also one failing integration test for module builder
=> fixed UI tests for module builder

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/Index.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Telerik.Sitefinity.Frontend.InlineClientAssets.csproj
=> Remove index css view

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockLinkSelectorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ContentBlock/ContentBlockWidgetEditWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertAnAnchor.cs, Tests/FeatherWidgets.TestUI.TestCases/ContentBlocks/LinkSelectorInsertLinkToEmailAddress.cs
- SelectTextInEditableArea is renamed to SelectLinkInEditableArea and is
changed to mark the link text with mouse drag
=> fixed tests for link selector

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Scripts/StyleSheet/designerview-simple.js
=> Cleared css value when widget is saved in different mode

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/StyleSheetController.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/StringResources/StyleSheetResources.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.cshtml
=> Css designer fixes

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/StringResources/StyleSheetResources.cs, Tests/FeatherWidgets.TestUnit/Resources/ResourcesTests.cs
=> Css resource tests

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/StyleSheetController.cs
=> handle css widget unknown action

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/JavaScript/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.cshtml
=> Css js widgets styles

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Scripts/JavaScript/designerview-simple.js, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/StringResources/JavaScriptResources.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/JavaScript/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/JavaScript/DesignerView.Simple.json
=> Added sf-file-url-field to the JavaScript widget designer

Tests/FeatherWidgets.TestIntegration/BlogPosts/BlogPostsWidgetTests.cs, Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj, Tests/FeatherWidgets.TestIntegration/TestCategories.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs, Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj
=> added integration test BlogPostsWidget_DisplayPostsFromSelectedBlogsOnly

SetupScripts/FeatherSetup.ps1, Tests/FeatherWidgets.TestIntegration/BlogPosts/BlogPostsWidgetTests.cs
updated feather setup script with Blogs.dll
=> added integration test BlogPostsWidget_DisplaySelectedBlogPosts

Tests/FeatherWidgets.TestIntegration/BlogPosts/BlogPostsWidgetTests.cs
BlogPostsWidget_DisplayAllPublishedBlogPostsFromAllBlogs
=> added integration test 

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/StyleSheetController.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/StringResources/StyleSheetResources.cs, Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj, Tests/FeatherWidgets.TestIntegration/InlineClientAssets/StyleSheetWidgetTests.cs, Tests/FeatherWidgets.TestIntegration/TestCategories.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/InlineClientAssets/StyleSheetControllerTests.cs, Tests/FeatherWidgets.TestUnit/InlineClientAssets/StyleSheetModelTests.cs, Tests/FeatherWidgets.TestUnit/Resources/ResourcesTests.cs
=> Css widget tests #896

Telerik.Sitefinity.Frontend.Identity/Mvc/Controllers/RegistrationController.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Profile/ProfileModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/IRegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Models/Registration/RegistrationViewModel.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/StringResources/RegistrationResources.cs, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/LoginForm.LoginForm.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Profile/Edit.ProfileEdit.cshtml, Telerik.Sitefinity.Frontend.Identity/Mvc/Views/Registration/Registration.RegistrationForm.cshtml
=> Awesome Email as Username update

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/StyleSheetController.cs
=> Fixed rendering of CSS widget in preview mode

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs
=> Refactor filter by date method

Tests/FeatherWidgets.TestIntegration/BlogPosts/BlogPostsWidgetNarrowSelectionTests.cs, Tests/FeatherWidgets.TestIntegration/BlogPosts/BlogPostsWidgetTests.cs, Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
added integration tests for Filter blog posts widget by tag and category
=> added integration tests

Tests/FeatherWidgets.TestUI.Arrangements/BlogPosts/AddBlogPostsWidgetToPageOpenSingleItemInExistingPage.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.TestCases/BlogPosts/BlogPostsWidgetOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherTestCategories.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj
UI test : AddBlogPostsWidgetToPageOpenSingleItemInExistingPage
=> Added UI test for Blog posts widget

Telerik.Sitefinity.Frontend.Comments/Mvc/Scritps/Comments/comments.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Telerik.Sitefinity.Frontend.Comments.csproj
=> Implemented listing and sorting

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/ICommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Integrate comments model

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/StyleSheetController.cs
=> Added description checking in isEmpty property

Tests/FeatherWidgets.TestIntegration/BlogPosts/BlogPostsWidgetListSettingsTests.cs, Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj
=> added new integration tests for BlogPostsWidgetListSettingsTests

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Scripts/JavaScript/designerview-simple.js, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Scripts/StyleSheet/designerview-simple.js
=> Fixed jserror

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Comments closed thread

Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifySelectedRolesInUsersListOnBootstrapPage.cs, Tests/FeatherWidgets.TestUI.TestCases/Identity/VerifySelectedUsersInUsersListWithSelectedSingleUserPage.cs
=> Fixed user first and last name in tests

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Media/MediaSelectorScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Media/MediaSelectorBaseWrapper.cs
=> Correct media ui tests

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/ICommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Telerik.Sitefinity.Frontend.Comments.csproj
=> Comments approval

Telerik.Sitefinity.Frontend.Comments/Mvc/Controllers/CommentsController.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/ICommentsModel.cs
=> Removed show comments property

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Search/SearchWrapper.cs
=> Fix search ui tests

Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/LanguageSelectorController.cs
https://github.com/Sitefinity/feather/issues/1612
=> Language selector fix 1612

Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/LanguageSelectorController.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/StringResources/LanguageSelectorResources.cs
https://github.com/Sitefinity/feather/issues/1617
=> Language selector fix 1617

Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/LanguageSelectorController.cs
https://github.com/Sitefinity/feather/issues/1621
=> Language selector icon fix

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListWidgetSettings.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-count.js
=> Js widget refactoring

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs
=> Fixed adding of new comment

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js
=> Added refresh on comment submit

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js
=> Everytime comment is rendered count is checked

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj, Tests/FeatherWidgets.TestIntegration/Identity/UsersList/UsersListWidgetPagingLimitTests.cs, Tests/FeatherWidgets.TestIntegration/Identity/UsersList/UsersListWidgetSortingTests.cs
=> Added integration tests for Users list

Telerik.Sitefinity.Frontend.Navigation/Mvc/Models/LanguageSelector/LanguageSelectorModel.cs
=> Bugfix #1626 - display current language in draft page

Telerik.Sitefinity.Frontend.Navigation/Mvc/Controllers/LanguageSelectorController.cs, Tests/FeatherWidgets.TestUnit/DummyClasses/LanguageSelector/DummyLanguageSelectorController.cs
=> Unit tests fix

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-count.js
Please review:
-  [x] @dzhenko
=> Fixed comments count error

Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/LanguageSelector/LanguageSelector.DropDownMenu.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/LanguageSelector/LanguageSelector.LanguageLinks.cshtml
=> Links desing mode

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Only using one date to track last comment

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Removed unused website field

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js
=> Separated comment count rendering concerns

ReferenceAssemblies/Telerik.Sitefinity.Frontend.XML, Telerik.Sitefinity.Frontend.Comments/Mvc/Controllers/CommentsController.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsCountInputModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/ICommentsModel.cs, Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/List.NewsList.cshtml
=> Granular allow #1644

Tests/FeatherWidgets.TestIntegration/DocumentsList/DocumentsListWidgetPagingLimitTests.cs, Tests/FeatherWidgets.TestIntegration/DocumentsList/DocumentsListWidgetSortingTests.cs, Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj, Tests/FeatherWidgets.TestIntegration/TestCategories.cs
=> Add new integration tests for documents list for limits and sorting

Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Changed resource

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js
=> Extracted methods from load comments

Telerik.Sitefinity.Frontend.Comments/Mvc/Controllers/CommentsController.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs
=> Fix comment error in template

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Comments bugs #1657 #1659 #1664

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js
=> Refresh captcha when validation fails

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListViewModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Changed subscribtion messages

Telerik.Sitefinity.Frontend.Navigation/Mvc/StringResources/LanguageSelectorResources.cs
=> Fix language selector resource

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Comments email subscription #1658

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListWidgetSettings.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/ICommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js
=> Date format #1660

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListViewModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Added server setting for disabling paging depending on comments settigns

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-count.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js
=> Comment count #1669

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js
=> date formatting issues

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListViewModel.cs, Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/List.NewsList.cshtml
=> News without comments #1673

Telerik.Sitefinity.Frontend.Navigation/Mvc/StringResources/LanguageSelectorResources.cs, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Breadcrumb/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/LanguageSelector/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/LanguageSelector/LanguageSelector.DropDownMenu.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/LanguageSelector/LanguageSelector.LanguageLinks.cshtml
=> Styles for designers and templates of language selector and breadscrumb

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> guest fields appear on focus

Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml
=> Changed views to new helpers

Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/List.NewsList.cshtml
=> clean comments news markup

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListViewModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/List.NewsList.cshtml
=> dynamic ids

Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/ContainerTemplates/DetailTemplateContainer.cshtml, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/ContainerTemplates/ListTemplateContainer.cshtml
=> Dynamic content comments

Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/List.NewsList.cshtml
=> removed unused usings

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj, Tests/FeatherWidgets.TestIntegration/ImageGallery/ImageGalleryWidgetPagingLimitTests.cs, Tests/FeatherWidgets.TestIntegration/ImageGallery/ImageGalleryWidgetSortingTests.cs
=> Add new tests for image gallery

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-count.js
=> fixed IE js error

Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Sitemap.cshtml
=> Replaced <b> tag with <strong> in navigation template

Tests/FeatherWidgets.TestIntegration/FeatherWidgets.TestIntegration.csproj, Tests/FeatherWidgets.TestIntegration/MediaGalleryWidgets/DocumentsListWidgetPagingLimitTests.cs, Tests/FeatherWidgets.TestIntegration/MediaGalleryWidgets/DocumentsListWidgetSortingTests.cs, Tests/FeatherWidgets.TestIntegration/MediaGalleryWidgets/ImageGalleryWidgetPagingLimitTests.cs, Tests/FeatherWidgets.TestIntegration/MediaGalleryWidgets/ImageGalleryWidgetSortingTests.cs, Tests/FeatherWidgets.TestIntegration/MediaGalleryWidgets/VideoGalleryWidgetPagingLimitTests.cs, Tests/FeatherWidgets.TestIntegration/MediaGalleryWidgets/VideoGalleryWidgetSortingTests.cs
=> Add video integration tests, pull all media test inder MediaGalleryWidgets folder

Tests/FeatherWidgets.TestIntegration/News/NewsWidgetDetailTests.cs
=> fix integration tests

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/rating.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
Please review:
In order to enable rating you should add the follwoing in the view:
````HTML
@Html.Script(Url.WidgetContent("Mvc/Scripts/Comments/rating.js"), "bottom", false)
<div data-sf-role="rating-container" class="rating">
</div>
````
In js:
````JavaScript
var rating = $('[data-sf-role="rating-container"]').mvcRating();
rating.setValue(3);
var currentRating = rating.getValue();
````
in css:
````CSS
.on{
color:Red !important;
}
.hover{
color:Orange !important;
}
.rating span 
{
cursor: pointer;
} 
````
=> Rating container

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Comments/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml
=> Changed markup of comment templates

ReferenceAssemblies/Telerik.Sitefinity.Frontend.XML, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/ContainerTemplates/DetailTemplateContainer.cshtml, Telerik.Sitefinity.Frontend.DynamicContent/WidgetTemplates/ContainerTemplates/ListTemplateContainer.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.News/MVC/Views/News/List.NewsList.cshtml
=> remove comments

Tests/FeatherWidgets.TestIntegration/Identity/LoginStatus/LoginTests.cs
=> Fixed integration test for verifying logout url in LoginStatus widget

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/ScriptsAndStyles/JavaScriptEditScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ScriptsAndStylesWidgets/JavaScriptWidgetEditWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ScriptsAndStyles/ScriptsAndStylesWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/ScriptsAndStyles/AddJavaScriptBeforeTheClosingBodyTag.cs, Tests/FeatherWidgets.TestUI.Arrangements/ScriptsAndStyles/SelectJavaScriptFileInJavaScriptWidget.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherTestCategories.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/AddJavaScriptBeforeTheClosingBodyTag.cs, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/AddJavaScriptWhereTheWidgetIsDropped.cs, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/JavaScriptWidgetOnPageTemplateAndAddDescription.cs, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/SelectJavaScriptFileInJavaScriptWidget.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs, Tests/FeatherWidgets.TestUtilities/Data/CssFiles/JavaScriptWidgetTest.js, Tests/FeatherWidgets.TestUtilities/FeatherWidgets.TestUtilities.csproj
=> Add new UI tests for javacript widget

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs
=> fix comments when login page is deleted

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Fixed comments when rating is not enabled

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Fixed show hide of name and email fields

Tests/Feather.Widgets.TestUI.Framework/Feather.Widgets.TestUI.Framework.csproj, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/ScriptsAndStyles/ScriptsAndStylesEditScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Pages/PageZoneEditorMediaWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/FrontendWrappesFacade.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/VideoGallery/VideoGalleryWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/VideoGallery/VideoGalleryWrapperFacade.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/VideoGallery/FilterVideosWithCategoryTagAndDateOnPage.cs, Tests/FeatherWidgets.TestUI.Arrangements/VideoGallery/SelectAllPublishedVideos.cs, Tests/FeatherWidgets.TestUI.Arrangements/VideoGallery/SelectAllPublishedVideosWithOverlayGalleryTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/VideoGallery/SelectSortedVideosWithChangedThumbnails.cs, Tests/FeatherWidgets.TestUI.Arrangements/VideoGallery/SelectVideosFromSelectedLibraryInSelectedPage.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherTestCategories.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/VideoGallery/FilterVideosWithCategoryTagAndDateOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/VideoGallery/SelectAllPublishedVideos.cs, Tests/FeatherWidgets.TestUI.TestCases/VideoGallery/SelectAllPublishedVideosWithOverlayGalleryTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/VideoGallery/SelectSortedVideosWithChangedThumbnails.cs, Tests/FeatherWidgets.TestUI.TestCases/VideoGallery/SelectVideosFromSelectedLibraryInSelectedPage.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs
=> Video gallery tests

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Comments styles

Telerik.Sitefinity.Frontend.Comments/Mvc/Controllers/ReviewsController.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/CommentsCount.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/ReviewsCount.Default.cshtml
=> Average rating

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsCountInputModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs
=> Fixed allows comments count depending on settings

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Refreshing of reviews when submitting added

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListWidgetResources.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/StringResources/CommentsWidgetResources.cs
=> Added validation for email in comments widget

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js
=> Fixed error in comments count

Telerik.Sitefinity.Frontend.News/MVC/Views/News/Detail.DetailPage.cshtml
=> Replaced string empty

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsListViewModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml
=> Added thread type

Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/SiteSelector/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/SiteSelector/SiteSelector.DropDownMenu.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/SiteSelector/SiteSelector.SiteLinks.cshtml
=> Site selector

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/CommentsCount.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/ReviewsCount.Default.cshtml
=> Use ratings and resources individually used for every comments wrapper

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/Reviews/rating.js
=> Fix for selecting rating in Firefox

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/MediaGallery/MediaGalleryFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ImageGallery/ImageGalleryWrapper.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/VideoGallery/VideoGalleryWrapper.cs
=> Refactor media wrappers

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Login message hidden if review is submited

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/ScriptsAndStylesWidgets/ScriptsAndStylesCommonWrapper.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/DuplicateAndDeleteJavaScriptWidgetOnPage.cs
=> Add test for JavaScript duplicate and delete widget

Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/SiteSelector/SiteSelector.DropDownMenu.cshtml, Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/SiteSelector/SiteSelector.SiteLinks.cshtml
=> Small changes to site selector templates

Telerik.Sitefinity.Frontend.InlineClientAssets/InterfaceMappings.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/EmbedCodeController.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Controllers/JavaScriptController.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Helpers/ScriptHelper.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/EmbedCode/EmbedCodeModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/EmbedCode/EmbedCodeViewModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Models/EmbedCode/IEmbedCodeModel.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Scripts/EmbedCode/designerview-simple.js, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/StringResources/EmbedCodeResources.cs, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/EmbedCode/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/EmbedCode/DesignerView.Simple.json, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/EmbedCode/Index.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Telerik.Sitefinity.Frontend.InlineClientAssets.csproj, Tests/FeatherWidgets.TestUnit/DummyClasses/InlineClientAssets/DummyEmbedCodeController.cs, Tests/FeatherWidgets.TestUnit/FeatherWidgets.TestUnit.csproj, Tests/FeatherWidgets.TestUnit/InlineClientAssets/EmbedCode/EmbedCodeControllerTests.cs
=> Embed code wdiget

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml
=> Error messages

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js
=> Items extracted to array from response

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Proper position of error messages

Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml
=> Reviews styles

Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml
=> Initially hidden template

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Moved captcha error above submit button

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Comments/Comments.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/ReviewsCount.Default.cshtml
=> Added styles for reviews and some changes to comments

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/ReviewsCount.Default.cshtml
=> Reviews extract template

Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/ReviewsCount.Default.cshtml
=> Removed anchor from wrapper

Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml
=> Ratings style

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Hide subscription if not logged in.

Telerik.Sitefinity.Frontend.Comments/Mvc/Models/CommentsModel.cs
=> Thread key set to empty string if on template

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-count.js
=> Always round current rating

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js, Telerik.Sitefinity.Frontend.Comments/Mvc/Views/Reviews/Reviews.Default.cshtml
=> Reviews count label hidden

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Proper reviews count

Telerik.Sitefinity.Frontend.Search/Mvc/Views/SearchResults/SearchResults.cshtml
=> fix search result select label for hybrid page

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Fixed #1798-Reviews Average should be styled

Telerik.Sitefinity.Frontend.Comments/Mvc/Scripts/comments-list.js
=> Hide write review on render

AssemblyInfoShare/SharedAssemblyInfo.cs
=> Version update

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/HierarchicalTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/IHierarchicalTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs
=> Taxa model impl

Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/ScriptsAndStyles/ScriptsAndStylesWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/ScriptsAndStyles/AddEmbedCodeWidgetToPageAndWriteAndRemoveJavaScript.cs, Tests/FeatherWidgets.TestUI.Arrangements/ScriptsAndStyles/WriteAndEditCssInEmbedCodeWidget.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/AddEmbedCodeWidgetToPageAndWriteAndRemoveJavaScript.cs, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/AddJavaScriptWhereTheWidgetIsDropped.cs, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/DuplicateAndDeleteEmbedCodeWidgetOnPage.cs, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/EmbedCodeWidgetOnPageTemplateAndAddDescription.cs, Tests/FeatherWidgets.TestUI.TestCases/ScriptsAndStyles/WriteAndEditCssInEmbedCodeWidget.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs
=> Add new tests for embed code widget

Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Blogs/Mvc/Views/BlogPost/List.BlogPostList.cshtml
=> Added comments in blog post widget

Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.PagesList.cshtml
=> Added comments/reviews to lists

Telerik.Sitefinity.Frontend.Lists/Mvc/Models/IListsModel.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/ExpandableListFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Lists/ExpandedListFrontend.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Frontend/Lists/ListsWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/FeatherWidgets.TestUI.Arrangements.csproj, Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyAnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyExpandedListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyListTemplatesOnBootstrap.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyPagesListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifySimpleListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/FeatherWidgets.TestUI.TestCases.csproj, Tests/FeatherWidgets.TestUI.TestCases/Lists/VerifyAnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/VerifyExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/VerifyExpandedListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/VerifyListTemplatesOnBootstrap.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/VerifyPagesListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/VerifySimpleListTemplate.cs, Tests/FeatherWidgets.TestUtilities/CommonOperations/Pages/PagesOperations.cs
=> Lists ui tests enhancement

Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/Detail.DetailPage.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.PagesList.cshtml, Telerik.Sitefinity.Frontend.Lists/Mvc/Views/Lists/List.SimpleList.cshtml
=> Moved comments count widget

Tests/Feather.Widgets.TestUI.Framework/Framework/ElementMap/Widgets/WidgetDesignerScreen.cs, Tests/Feather.Widgets.TestUI.Framework/Framework/Wrappers/Backend/Widgets/WidgetDesignerWrapper.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyExpandableListTemplate.cs, Tests/FeatherWidgets.TestUI.Arrangements/Lists/VerifyListTemplatesOnBootstrap.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/VerifyAnchorListTemplate.cs, Tests/FeatherWidgets.TestUI.TestCases/Lists/VerifyListTemplatesOnBootstrap.cs
=> Edit widget designer on bootstrap

Telerik.Sitefinity.Frontend.Identity/Mvc/Views/UsersList/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/JavaScript/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.cshtml
Improvements in css and js widget designers
=> Improvements in css and js widget designers

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/JavaScript/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/StyleSheet/DesignerView.Simple.cshtml
=> Comments blogs lists

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/FlatTaxonomy/FlatTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonViewModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.CloudList.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.TagCloud.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Telerik.Sitefinity.Frontend.Taxonomies.csproj
=> Added TagCloud and CloudList templates

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/FlatTaxonomy/FlatTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/HierarchicalTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs
=> Field name fix

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/FlatTaxonomy/FlatTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/HierarchicalTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs
=> Taxon url refactoring

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs
=> Custom taxonomy fix

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/DesignerView.Simple.cshtml
=> Sorting options

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/HierarchicalTaxonomyModel.cs
=> Categories sorting fix

Telerik.Sitefinity.Frontend.Taxonomies/Helpers/ContentTypeExtensions.cs
=> Uninstalled modules

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Controllers/FlatTaxonomyController.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Controllers/HierarchicalTaxonomyController.cs
=> Renamed flat

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/DesignerView.Simple.cshtml
=> Changes to Tags designer markup

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/FlatTaxonomy/FlatTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/FlatTaxonomy/IFlatTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/HierarchicalTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/HierarchicalTaxonomy/IHierarchicalTaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyViewModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.CloudList.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.SimpleList.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.TagCloud.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/HierarchicalTaxonomy.CategoriesList.cshtml
=> 1. Classification: Css classes cannot be saved

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs
=> Sorting fix

Telerik.Sitefinity.Frontend.InlineClientAssets/Mvc/Views/EmbedCode/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.CloudList.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.SimpleList.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.TagCloud.cshtml
=> Embed code tags style

ReferenceAssemblies/Telerik.Sitefinity.Frontend.XML, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/DesignerModelHelper.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/StringResources/FlatTaxonomyResources.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/StringResources/HierarchicalTaxonomyResources.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Telerik.Sitefinity.Frontend.Taxonomies.csproj
https://github.com/Sitefinity/feather-widgets/issues/1154
=> Taxonomy resources fix

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.CloudList.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.SimpleList.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/FlatTaxonomy.TagCloud.cshtml
=> Tags widget styles

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Models/TaxonomyModel.cs, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Scripts/FlatTaxonomy/designerview-simple.js, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Scripts/HierarchicalTaxonomy/designerview-simple.js, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/DesignerView.Simple.cshtml
https://github.com/Sitefinity/feather/issues/1837
=> Manual sorting #1837

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/FlatTaxonomy/DesignerView.Simple.cshtml, Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Views/HierarchicalTaxonomy/DesignerView.Simple.cshtml
=> Taxa languages

Telerik.Sitefinity.Frontend.Taxonomies/Mvc/Scripts/HierarchicalTaxonomy/designerview-simple.js
https://github.com/Sitefinity/feather/issues/1843
=> Categories designer fix
